// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : axi_interface.mv
// Perintah  : maria mgen axi_interface.mv
// ─────────────────────────────────────────────────────────────

`include "axi_interface.svh"

module axi_slave (
    axi_lite axi_if,
    output bit done
);
    logic [3:0] cnt;

    // ── logika sekuensial ──
    always_ff @(posedge axi_if.clk) begin
        if (axi_if.awvalid && axi_if.awready) begin
            cnt <= cnt + 1;
            done <= 1;
        end else begin
            done <= 0;
        end
    end

    // ── logika kombinasional ──
    always_comb begin
        axi_if.awready = axi_if.awvalid;
    end
endmodule

module tb_axi (
    input  bit clk
);
    axi_lite bus;
    bit done;

    axi_lite u_axi (
        .clk     (clk),
        .awaddr  (32'h00),
        .awvalid (1'b1),
        .awready (1'b1),
        .wdata   (32'hdead_beef),
        .wready  (1'b1)
    );

    axi_slave u_slave (
        .axi_if (bus),
        .done   (done)
    );

    // ── initial ──
    initial begin
        $display("tb_axi: interface contoh siap");
    end
endmodule
