// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : axi_interface.mv
// Perintah  : maria mgen axi_interface.mv
// ─────────────────────────────────────────────────────────────

`ifndef AXI_INTERFACE_SVH
`define AXI_INTERFACE_SVH

interface axi_lite;
    bit clk;
    logic [31:0] awaddr;
    bit awvalid;
    bit awready;
    logic [31:0] wdata;
    bit wready;
    modport slave (input awaddr, awvalid, wdata, output awready, wready);
    modport master (output awaddr, awvalid, wdata, input awready, wready);
endinterface

`endif
