// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : cast.mv
// Perintah  : maria mgen cast.mv
// ─────────────────────────────────────────────────────────────

`ifndef CAST_SVH
`define CAST_SVH

typedef logic [15:0] Word16;

`endif
