// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : class_model.mv
// Perintah  : maria mgen class_model.mv
// ─────────────────────────────────────────────────────────────


class counter_model;
    logic [31:0] value;
    logic [31:0] limit;
    bit clk;

    constraint c {
        value < limit;
    }

    function new();
        value = 0;
        limit = 100;
    endfunction

    function bit is_done();
        return value >= limit;
    endfunction

    task tick(inout logic [31:0] n);
        repeat (n) @(posedge clk) value = value + 1;
    endtask
endclass
