// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : counter.mv
// Perintah  : maria mgen counter.mv
// ─────────────────────────────────────────────────────────────

`ifndef COUNTER_SVH
`define COUNTER_SVH

package counter_pkg;
    typedef logic [15:0] Addr;
    typedef struct packed {
        bit   valid;
        Addr  addr;
        logic [31:0] data;
    } Packet;
endpackage

`endif
