// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : param_counter.mv
// Perintah  : maria mgen param_counter.mv
// ─────────────────────────────────────────────────────────────


module counter_w #(
    parameter WIDTH = 4,
    parameter STEP = 1
) (
    input  bit clk,
    input  bit rst_n,
    output logic [WIDTH - 1:0] count
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            count <= '0;
        end else begin
            count <= count + STEP;
        end
    end
endmodule

module tb_param (

);
    bit clk, rst_n;
    logic [3:0] cnt4;
    logic [7:0] cnt8;

    counter_w u_small (
        .clk   (clk),
        .rst_n (rst_n),
        .count (cnt4)
    );

    counter_w u_big #(.WIDTH(8), .STEP(2)) (
        .clk   (clk),
        .rst_n (rst_n),
        .count (cnt8)
    );

    // ── initial ──
    initial begin
        clk = 0;
        rst_n = 0;
        #10 rst_n = 1;
        repeat (10) begin
            @(posedge clk) begin
            end
        end
        #1 begin
            if (cnt8 == 8'd20 && cnt4 == 4'd10) begin
                $display("TB_PARAM_OK cnt8=%0d cnt4=%0d", cnt8, cnt4);
            end else begin
                $display("TB_PARAM_BROKEN cnt8=%0d cnt4=%0d", cnt8, cnt4);
            end
        end
        $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end
endmodule
