// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : traffic.mv
// Perintah  : maria mgen traffic.mv
// ─────────────────────────────────────────────────────────────

`ifndef TRAFFIC_SVH
`define TRAFFIC_SVH

package traffic_pkg;
    typedef enum logic [1:0] { RED, GREEN, YELLOW } State;
endpackage

`endif
