// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : type_param.mv
// Perintah  : maria mgen type_param.mv
// ─────────────────────────────────────────────────────────────

`ifndef TYPE_PARAM_SVH
`define TYPE_PARAM_SVH

typedef logic [15:0] Word16;

`endif
