//! GTKWave Save File Generator — membuat .gtkw file untuk membuka VCD/FST.
//!
//! Format GTKWave save file (.gtkw) adalah format teks yang menyimpan
//! konfigurasi tampilan: signal mana yang ditampilkan, grouping, warna, dll.
//!
//! Gunakan `--gtkw <path>` untuk generate file .gtkw yang merujuk ke VCD/FST output.

use maria_ir::IrDesign;

/// Generate a GTKWave save file content.
///
/// Membuat file .gtkw yang membuka file VCD atau FST dengan signal-signal
/// yang terorganisir berdasarkan hierarki module.
pub fn generate_gtkw(
    waveform_path: &str,
    design: &IrDesign,
) -> String {
    let mut content = String::new();

    // ── Header ──
    content.push_str("[awave]\n");
    content.push_str("# GTKWave save file generated by Maria RTL Simulator\n");
    content.push_str("# Open with: gtkwave <file>.fst\n\n");

    // ── Font & Display Settings ──
    content.push_str("fontname=\"Monospace 10\"\n");
    content.push_str("use_stdout=0\n");
    content.push_str("dumpfile=");
    content.push_str(waveform_path);
    content.push('\n');

    // Determine format from extension
    if waveform_path.ends_with(".fst") {
        content.push_str("dumpfiletype=fst\n");
    } else {
        content.push_str("dumpfiletype=vcd\n");
    }

    content.push('\n');

    // ── Signal Groups by Scope ──
    // Group signals by their scope path
    use std::collections::HashMap;
    let mut scope_map: HashMap<Vec<String>, Vec<(String, usize)>> = HashMap::new();

    for sig in &design.top.signals {
        let name_str = sig.name.as_str();
        let parts: Vec<&str> = name_str.rsplitn(2, '.').collect();
        let (scope_parts, bare_name) = if parts.len() == 2 {
            let scope: Vec<String> = parts[1].split('.').map(|s| s.to_string()).collect();
            (scope, parts[0].to_string())
        } else {
            (vec![], name_str.to_string())
        };

        scope_map
            .entry(scope_parts)
            .or_default()
            .push((bare_name, sig.width));
    }

    // Sort scopes for consistent ordering
    let mut sorted_scopes: Vec<Vec<String>> = scope_map.keys().cloned().collect();
    sorted_scopes.sort();

    // Write signals grouped by scope
    let top_name = design.top.name.as_str();
    let mut signal_count = 0u32;

    content.push_str(&format!("[{}]\n", top_name));

    for scope_path in &sorted_scopes {
        let full_scope_name = if scope_path.is_empty() {
            top_name.to_string()
        } else {
            format!("{}.{}", top_name, scope_path.join("."))
        };

        content.push_str(&format!("  [{}]\n", full_scope_name));

        let sigs = scope_map.get(scope_path).unwrap();
        for (bare_name, _width) in sigs {
            content.push_str(&format!(
                "    {} {}.{}\n",
                signal_count,
                full_scope_name,
                bare_name
            ));
            signal_count += 1;
        }
    }

    // ── Time Configuration ──
    content.push_str("\n# Time configuration\n");
    content.push_str("time_start=0\n");

    // ─── Tree mode ───
    content.push_str("\n# Display mode\n");
    content.push_str("tree_mode=1\n"); // Show hierarchy tree
    content.push_str("show_clocks=1\n");
    content.push_str("show_cycles=1\n");

    content
}

/// Save GTKWave save file to disk.
pub fn save_gtkw(path: &str, waveform_path: &str, design: &IrDesign) -> Result<(), String> {
    let content = generate_gtkw(waveform_path, design);
    std::fs::write(path, &content)
        .map_err(|e| format!("cannot write GTKW file '{}': {}", path, e))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use maria_core::intern::Symbol;
    use maria_ir::*;

    fn make_test_design() -> IrDesign {
        let mut design = IrDesign::default();
        design.top.name = Symbol::intern("test_top");
        design.top.signals = vec![
            SignalInfo {
                name: Symbol::intern("clk"),
                width: 1,
                ..Default::default()
            },
            SignalInfo {
                name: Symbol::intern("rst_n"),
                width: 1,
                ..Default::default()
            },
            SignalInfo {
                name: Symbol::intern("top.u_sub.count"),
                width: 8,
                ..Default::default()
            },
        ];
        design
    }

    #[test]
    fn test_gtkw_generate() {
        let design = make_test_design();
        let gtkw = generate_gtkw("output.fst", &design);
        assert!(gtkw.contains("dumpfile=output.fst"), "should reference waveform file");
        assert!(gtkw.contains("dumpfiletype=fst"), "should detect fst format");
        assert!(gtkw.contains("clk"), "should include clk signal");
        assert!(gtkw.contains("rst_n"), "should include rst_n signal");
        assert!(gtkw.contains("count"), "should include count signal");
        assert!(gtkw.contains("test_top"), "should include top module name");
        assert!(gtkw.starts_with("[awave]"), "should start with [awave] header");
    }

    #[test]
    fn test_gtkw_vcd_detection() {
        let design = make_test_design();
        let gtkw = generate_gtkw("output.vcd", &design);
        assert!(gtkw.contains("dumpfiletype=vcd"), "should detect vcd format");
    }
}
