//! FEAT-22: Automated Testbench Generation — scaffold testbench from module ports.
//!
//! Generates a basic SystemVerilog testbench skeleton from module interface.
//! Creates clock, reset, DUT instantiation, and basic stimulus patterns.

use serde::{Deserialize, Serialize};

/// Port direction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PortDir {
    Input,
    Output,
    InOut,
}

/// Port info for testbench generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortInfo {
    pub name: String,
    pub dir: PortDir,
    pub width: u32,
    pub bus_range: Option<(u32, u32)>,
}

/// Testbench configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TbConfig {
    pub module_name: String,
    pub instance_name: String,
    pub clock_name: String,
    pub clock_period: u32,
    pub reset_name: Option<String>,
    pub reset_active_high: bool,
    pub simulation_time: u32,
    pub dump_vcd: bool,
    pub include_checks: bool,
}

impl Default for TbConfig {
    fn default() -> Self {
        TbConfig {
            module_name: "dut".into(),
            instance_name: "u_dut".into(),
            clock_name: "clk".into(),
            clock_period: 10,
            reset_name: Some("rst_n".into()),
            reset_active_high: false,
            simulation_time: 1000,
            dump_vcd: true,
            include_checks: true,
        }
    }
}

fn push(tb: &mut String, s: &str) {
    tb.push_str(s);
}

/// Generate testbench from ports.
pub fn generate_tb(config: &TbConfig, ports: &[PortInfo]) -> String {
    let mut tb = String::new();

    push(&mut tb, "// Auto-generated testbench for ");
    push(&mut tb, &config.module_name);
    push(&mut tb, "\n// Generated by maria tbgen\n\n");

    push(&mut tb, "module tb;\n\n");

    let half = config.clock_period / 2;
    push(&mut tb, &format!("    // Clock generation ({}ns period)\n", config.clock_period));
    push(&mut tb, &format!("    reg {};\n", config.clock_name));
    push(&mut tb, &format!("    always #{} {} = ~{};\n\n", half, config.clock_name, config.clock_name));

    if let Some(rst) = &config.reset_name {
        push(&mut tb, "    // Reset\n");
        push(&mut tb, &format!("    reg {};\n\n", rst));
    }

    push(&mut tb, "    // DUT signals\n");
    for port in ports {
        let width_str = if port.width > 0 {
            if let Some((msb, lsb)) = port.bus_range {
                format!(" [{}:{}]", msb, lsb)
            } else {
                format!(" [{}:0]", port.width - 1)
            }
        } else {
            String::new()
        };
        let type_name = match port.dir {
            PortDir::Input => "reg",
            PortDir::Output => "wire",
            PortDir::InOut => "wire",
        };
        push(&mut tb, &format!("    {}{} {};\n", type_name, width_str, port.name));
    }
    push(&mut tb, "\n");

    push(&mut tb, &format!("    // DUT instantiation\n"));
    push(&mut tb, &format!("    {} {} (\n", config.module_name, config.instance_name));
    for (i, port) in ports.iter().enumerate() {
        let comma = if i < ports.len() - 1 { "," } else { "" };
        push(&mut tb, &format!("        .{}({}){}\n", port.name, port.name, comma));
    }
    push(&mut tb, "    );\n\n");

    if config.dump_vcd {
        push(&mut tb, "    // Waveform dump\n");
        push(&mut tb, "    initial begin\n");
        let vcd_file = format!("{}.vcd", config.module_name);
        push(&mut tb, "        $dumpfile(\"");
        push(&mut tb, &vcd_file);
        push(&mut tb, "\");\n");
        push(&mut tb, "        $dumpvars(0, tb);\n");
        push(&mut tb, "    end\n\n");
    }

    push(&mut tb, "    // Stimulus\n");
    push(&mut tb, "    initial begin\n");
    if let Some(rst) = &config.reset_name {
        if config.reset_active_high {
            push(&mut tb, &format!("        {} = 1;\n", rst));
            push(&mut tb, &format!("        #{};\n", config.clock_period * 5));
            push(&mut tb, &format!("        {} = 0;\n", rst));
        } else {
            push(&mut tb, &format!("        {} = 0;\n", rst));
            push(&mut tb, &format!("        #{};\n", config.clock_period * 5));
            push(&mut tb, &format!("        {} = 1;\n", rst));
        }
        push(&mut tb, &format!("        #{};\n\n", config.clock_period * 5));
    }

    for port in ports {
        if matches!(port.dir, PortDir::Input) && port.width <= 8 {
            push(&mut tb, &format!("        {} = 0;\n", port.name));
            push(&mut tb, &format!("        #{};\n", config.clock_period * 2));
            push(&mut tb, &format!("        {} = 1;\n", port.name));
            push(&mut tb, &format!("        #{};\n", config.clock_period * 2));
        }
    }

    push(&mut tb, &format!("\n        #{};\n", config.simulation_time));
    push(&mut tb, "        $display(\"TESTBENCH COMPLETE\");\n");
    push(&mut tb, "        $finish;\n");
    push(&mut tb, "    end\n\n");

    if config.include_checks {
        push(&mut tb, "    // Basic checks\n");
        push(&mut tb, "    initial begin\n");
        push(&mut tb, "        repeat(100) @(posedge ");
        push(&mut tb, &config.clock_name);
        push(&mut tb, ");\n");
        push(&mut tb, "        $display(\"Simulation ran for 100 cycles without hanging\");\n");
        push(&mut tb, "    end\n\n");
    }

    push(&mut tb, "endmodule\n");
    tb
}

/// Quick generate from simple port list.
pub fn quick_tb(module_name: &str, inputs: &[(&str, u32)], outputs: &[(&str, u32)]) -> String {
    let mut ports = Vec::new();
    for (name, width) in inputs {
        ports.push(PortInfo {
            name: name.to_string(),
            dir: PortDir::Input,
            width: *width,
            bus_range: if *width > 1 { Some((*width - 1, 0)) } else { None },
        });
    }
    for (name, width) in outputs {
        ports.push(PortInfo {
            name: name.to_string(),
            dir: PortDir::Output,
            width: *width,
            bus_range: if *width > 1 { Some((*width - 1, 0)) } else { None },
        });
    }
    let config = TbConfig {
        module_name: module_name.to_string(),
        ..TbConfig::default()
    };
    generate_tb(&config, &ports)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_tb_generation() {
        let inputs = vec![("clk", 1), ("rst_n", 1), ("a", 8), ("b", 8)];
        let outputs = vec![("y", 8)];
        let tb = quick_tb("adder", &inputs, &outputs);
        assert!(tb.contains("module tb;"));
        assert!(tb.contains("adder u_dut"));
        assert!(tb.contains(".clk(clk)"));
        assert!(tb.contains(".y(y)"));
        assert!(tb.contains("$dumpfile"));
        assert!(tb.contains("$finish"));
    }

    #[test]
    fn test_tb_with_bus() {
        let ports = vec![
            PortInfo { name: "data".into(), dir: PortDir::Input, width: 32, bus_range: Some((31, 0)) },
            PortInfo { name: "valid".into(), dir: PortDir::Input, width: 1, bus_range: None },
        ];
        let config = TbConfig { module_name: "my_mod".into(), ..TbConfig::default() };
        let tb = generate_tb(&config, &ports);
        assert!(tb.contains("[31:0]"));
        assert!(tb.contains("reg [31:0] data"));
    }

    #[test]
    fn test_tb_no_vcd() {
        let config = TbConfig { dump_vcd: false, ..TbConfig::default() };
        let tb = generate_tb(&config, &[]);
        assert!(!tb.contains("$dumpfile"));
    }

    #[test]
    fn test_quick_tb() {
        let tb = quick_tb("counter", &[("clk", 1), ("en", 1)], &[("count", 4)]);
        assert!(tb.contains("counter u_dut"));
        assert!(tb.contains("[3:0] count"));
    }
}
