// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : dut.mv
// Perintah  : maria mgen dut.mv
// ─────────────────────────────────────────────────────────────


module memory_dut (
    mem_if axi,
    input  bit rst_n,
    output State st,
    output Addr addr
);
    import chip_types::*;

    // ── logika sekuensial ──
    always_ff @(posedge axi.clk or negedge rst_n) begin
        if (!rst_n) begin
            addr <= '0;
            st <= IDLE;
        end else begin
            addr <= addr + 1;
            st <= WR;
        end
    end

    // ── logika kombinasional ──
    always_comb begin
        axi.dout = axi.din;
    end
endmodule
