// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : types.mv
// Perintah  : maria mgen types.mv
// ─────────────────────────────────────────────────────────────

`ifndef TYPES_SVH
`define TYPES_SVH

package chip_types;
    typedef logic [15:0] Addr;
    typedef logic [31:0] Data;
    typedef enum logic [1:0] { IDLE, WR, RD } State;
endpackage

interface mem_if;
    bit clk;
    logic [15:0] addr;
    bit we;
    logic [31:0] din;
    logic [31:0] dout;
    modport slave (input addr, we, din, output dout);
    modport master (output addr, we, din, input dout);
endinterface

`endif
