//! Standalone HTML Waveform Viewer — menghasilkan file HTML yang bisa
//! membuka output CSV sebagai waveform viewer.
//!
//! File HTML self-contained (inline CSS + JS), bisa dibuka di browser
//! tanpa dependensi eksternal.
//!
//! Gunakan `--waveform-html-viewer` untuk generate viewer yang merujuk ke CSV.

use crate::ir::IrDesign;

/// Generate a standalone HTML waveform viewer.
///
/// The HTML file includes inline CSS and JavaScript that:
/// 1. Reads the CSV file (loaded as text)
/// 2. Parses signal values
/// 3. Renders a basic waveform view (1 state per row)
///
/// Returns the complete HTML content as a string.
pub fn generate_html_viewer(csv_path: &str, design: &IrDesign) -> String {
    let signal_names: Vec<String> = design
        .top
        .signals
        .iter()
        .map(|s| s.name.to_string())
        .collect();

    let signal_list_js = signal_names
        .iter()
        .map(|n| format!("\"{}\"", n.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Waveform Viewer - {design_name}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Consolas', 'Courier New', monospace; background: #1a1a2e; color: #e0e0e0; }}
  .container {{ max-width: 1400px; margin: 0 auto; padding: 20px; }}
  h1 {{ color: #00d4ff; font-size: 18px; margin-bottom: 16px; border-bottom: 1px solid #333; padding-bottom: 8px; }}
  .toolbar {{ display: flex; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; align-items: center; }}
  .toolbar label {{ color: #aaa; font-size: 13px; }}
  .toolbar input[type="range"] {{ width: 200px; background: #333; height: 4px; }}
  .toolbar input[type="text"] {{ background: #16213e; border: 1px solid #333; color: #e0e0e0; padding: 4px 8px; font-family: monospace; }}
  .toolbar button {{ background: #0f3460; color: #00d4ff; border: 1px solid #00d4ff; padding: 6px 14px; cursor: pointer; font-family: monospace; }}
  .toolbar button:hover {{ background: #16213e; }}
  .stats {{ color: #888; font-size: 12px; margin-bottom: 12px; }}
  .waveform {{ overflow-x: auto; overflow-y: auto; max-height: 80vh; border: 1px solid #333; background: #16213e; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 12px; }}
  th {{ background: #0f3460; color: #00d4ff; padding: 6px 10px; text-align: left; font-weight: normal; border-bottom: 2px solid #00d4ff; position: sticky; top: 0; z-index: 10; }}
  th.signal-name {{ min-width: 160px; }}
  th.time-col {{ min-width: 60px; text-align: right; }}
  td {{ padding: 3px 10px; border-bottom: 1px solid #2a2a3e; white-space: nowrap; }}
  td.time {{ color: #666; text-align: right; font-size: 11px; }}
  td.val-0 {{ color: #ff6b6b; }}
  td.val-1 {{ color: #51cf66; }}
  td.val-x {{ color: #ffd43b; }}
  td.val-z {{ color: #9775fa; }}
  .footer {{ margin-top: 20px; color: #555; font-size: 11px; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  <h1>📊 Waveform Viewer — {design_name}</h1>
  <div class="toolbar">
    <label>🔍 Filter:</label>
    <input type="text" id="filter" placeholder="signal name..." oninput="applyFilter()">
    <label>📏 Zoom:</label>
    <input type="range" id="zoom" min="1" max="5" value="1" oninput="applyZoom()">
    <button onclick="resetView()">Reset</button>
    <span id="info" class="stats">Loading...</span>
  </div>
  <div class="stats" id="stats-bar">Preparing waveform data...</div>
  <div class="waveform" id="waveform-container">
    <div id="loading">Loading CSV: {csv_path}...</div>
  </div>
  <div class="footer">Generated by Maria RTL Simulator | CSV: {csv_path}</div>
</div>

<script>
const SIGNAL_NAMES = [{signal_list_js}];
const CSV_PATH = "{csv_path}";

async function loadCSV() {{
  try {{
    const resp = await fetch(CSV_PATH);
    if (!resp.ok) throw new Error(`HTTP ${{resp.status}}`);
    const text = await resp.text();
    return text;
  }} catch(e) {{
    document.getElementById('loading').innerHTML =
      `<span style="color:#ff6b6b">⚠️ Cannot load CSV: ${{e.message}}<br>
      Make sure the CSV file exists at: <code>${{CSV_PATH}}</code><br>
      In browsers, CSV must be served from a web server (not file://) due to CORS.</span>`;
    throw e;
  }}
}}

function parseCSV(text) {{
  const lines = text.trim().split('\\n');
  if (lines.length < 2) return {{ headers: [], data: [] }};
  const headers = lines[0].split(',');
  const data = [];
  for (let i = 1; i < lines.length; i++) {{
    const vals = lines[i].split(',');
    const time = parseInt(vals[0]);
    const signals = vals.slice(1);
    data.push({{ time, signals }});
  }}
  return {{ headers, data }};
}}

function renderTable(data, signalNames) {{
  const container = document.getElementById('waveform-container');
  if (data.length === 0) {{
    container.innerHTML = '<div style="padding:20px;color:#888;">No data loaded.</div>';
    return;
  }}
  const filter = document.getElementById('filter').value.toLowerCase();
  const zoom = parseInt(document.getElementById('zoom').value);

  // Filter signal names
  const filtered = signalNames.map((name, idx) => ({{ name, idx }}))
    .filter(s => !filter || s.name.toLowerCase().includes(filter));

  let html = '<table><thead><tr><th class="time-col">Time</th>';
  for (const s of filtered) {{
    html += `<th class="signal-name">${{s.name}}</th>`;
  }}
  html += '</tr></thead><tbody>';

  // Show every Nth row based on zoom
  const step = zoom;
  for (let i = 0; i < data.length; i += step) {{
    const row = data[i];
    html += `<tr><td class="time">${{row.time}}</td>`;
    for (const s of filtered) {{
      const val = s.idx < row.signals.length ? row.signals[s.idx] : 'x';
      const cssClass = val === '0' ? 'val-0' : val === '1' ? 'val-1' : val === 'x' ? 'val-x' : val === 'z' ? 'val-z' : '';
      html += `<td class="${{cssClass}}">${{val.length > 4 ? val.substring(0, 4)+'..' : val}}</td>`;
    }}
    html += '</tr>';
  }}
  html += '</tbody></table>';
  container.innerHTML = html;

  // Update stats
  const numSignals = signalNames.length;
  const numTimes = data.length;
  document.getElementById('stats-bar').textContent =
    `${{numSignals}} signals × ${{numTimes}} time steps (showing every ${{step}}th)`;
  document.getElementById('info').textContent =
    `${{data.length}} rows | ${{filtered.length}} signals shown`;
}}

function applyFilter() {{
  loadCSV().then(text => {{
    const {{ data }} = parseCSV(text);
    renderTable(data, SIGNAL_NAMES);
  }}).catch(() => {{}});
}}

function applyZoom() {{
  applyFilter();
}}

function resetView() {{
  document.getElementById('filter').value = '';
  document.getElementById('zoom').value = '1';
  applyFilter();
}}

// Initialize
loadCSV().then(text => {{
  const {{ data }} = parseCSV(text);
  renderTable(data, SIGNAL_NAMES);
}}).catch(() => {{}});
</script>
</body>
</html>"#,
        design_name = design.top.name.as_str(),
        csv_path = csv_path,
        signal_list_js = signal_list_js,
    )
}

/// Save HTML viewer to file.
pub fn save_html_viewer(html_path: &str, csv_path: &str, design: &IrDesign) -> Result<(), String> {
    let html = generate_html_viewer(csv_path, design);
    std::fs::write(html_path, &html)
        .map_err(|e| format!("cannot write HTML viewer '{}': {}", html_path, e))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::intern::Symbol;
    use crate::ir::*;

    fn make_design() -> IrDesign {
        let mut design = IrDesign::default();
        design.top.name = Symbol::intern("test_top");
        design.top.signals = vec![
            SignalInfo {
                name: Symbol::intern("clk"),
                width: 1,
                ..Default::default()
            },
            SignalInfo {
                name: Symbol::intern("data"),
                width: 8,
                ..Default::default()
            },
        ];
        design
    }

    #[test]
    fn test_html_viewer_generate() {
        let design = make_design();
        let html = generate_html_viewer("output.csv", &design);
        assert!(html.contains("test_top"), "should contain design name");
        assert!(html.contains("output.csv"), "should reference CSV file");
        assert!(html.contains("clk"), "should contain clk signal");
        assert!(html.contains("data"), "should contain data signal");
        assert!(html.contains("Waveform Viewer"), "should have title");
        assert!(html.contains("</html>"), "should be valid HTML");
    }

    #[test]
    fn test_html_viewer_save() {
        use std::io::Write;
        let dir = std::env::temp_dir().join("maria_html_viewer_test");
        let _ = std::fs::create_dir_all(&dir);
        let path = dir.join("viewer.html");

        let design = make_design();
        save_html_viewer(path.to_str().unwrap(), "output.csv", &design).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("test_top"));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
