//! Emisi netlist → `netlist.v` (Verilog structural) + `.mvnet` (teks
//! deterministik) + summary (SYNTHESIS.md §13/§16).
//!
//! `netlist.v` memuat library sel generik (definisi modul primitif
//! technology-agnostik) + instansiasi top. Bisa disimulasikan engine Maria
//! (semua sel pakai `assign`/`always_ff` — tidak ada konstruk eksotis).

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::cell::{CellInstance, CellKind};
use crate::net::{Netlist, PortDir};

/// Emisi Verilog structural lengkap (library + top).
pub fn emit_verilog(nl: &Netlist) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "// Generated by maria synth — generic netlist (SYNTHESIS.md §13)"
    );
    let _ = writeln!(
        s,
        "// DO NOT EDIT. Top: {} — {} cells, {} nets.",
        nl.name.as_str(),
        nl.cells.len(),
        nl.nets.len()
    );
    let _ = writeln!(s);

    // ── Library sel generik (unik per spesifikasi) ──
    let mut kinds: BTreeSet<String> = BTreeSet::new();
    for c in &nl.cells {
        // Concat/Buffer di-emit sebagai assign langsung (bukan modul).
        if matches!(c.kind, CellKind::Concat | CellKind::Buffer) {
            continue;
        }
        kinds.insert(c.kind.module_key());
    }
    for key in &kinds {
        let kind = kind_from_key(&nl, key);
        let _ = writeln!(s, "{}", cell_module(&kind));
        let _ = writeln!(s);
    }
    if !kinds.is_empty() {
        let _ = writeln!(s);
    }

    // ── Top module ──
    let port_names: Vec<String> = nl
        .ports
        .iter()
        .map(|p| p.name.as_str().to_string())
        .collect();
    let _ = writeln!(s, "module {}({});", nl.name.as_str(), port_names.join(", "));
    for p in &nl.ports {
        let dir = match p.dir {
            PortDir::Input => "input",
            PortDir::Output => "output",
            PortDir::Inout => "inout",
        };
        if p.width > 1 {
            let _ = writeln!(s, "  {} [{}:0] {};", dir, p.width - 1, p.name.as_str());
        } else {
            let _ = writeln!(s, "  {} {};", dir, p.name.as_str());
        }
    }

    // Wire net internal (bukan port). Konstanta juga jadi wire + assign
    // (bukan literal di koneksi pin) — engine Maria tidak mendukung literal
    // pada port instance; wire ber-const lebih netlist-like dan portabel.
    for net in &nl.nets {
        let is_port = nl.ports.iter().any(|p| p.name == net.name);
        if is_port {
            continue;
        }
        if net.width > 1 {
            let _ = writeln!(s, "  wire [{}:0] {};", net.width - 1, net.name.as_str());
        } else {
            let _ = writeln!(s, "  wire {};", net.name.as_str());
        }
    }
    let _ = writeln!(s);

    // Konstanta → assign (driver net, bukan literal di pin).
    for net in &nl.nets {
        if let Some(v) = net.const_value {
            let lit = const_lit(net.width, v);
            let _ = writeln!(s, "  assign {} = {};", net.name.as_str(), lit);
        }
    }

    // Instansiasi sel.
    for c in &nl.cells {
        if matches!(c.kind, CellKind::Concat | CellKind::Buffer) {
            emit_inline_assign(&mut s, c, nl);
        } else {
            emit_instance(&mut s, c, nl);
        }
    }

    let _ = writeln!(s, "endmodule");
    s
}

/// Temukan kind sel dengan module key tertentu (untuk emit library).
fn kind_from_key(nl: &Netlist, key: &str) -> CellKind {
    nl.cells
        .iter()
        .map(|c| c.kind.clone())
        .find(|k| k.module_key() == key)
        .expect("module key dibangun dari sel nyata — harus ketemu")
}

/// Definisi modul primitif generik untuk sebuah kind.
///
/// Aturan lebar: `W` = lebar operand (dari `CellInstance.in_width`).
/// - Compare/reduce: output 1 bit, input `[W-1:0]`.
/// - Mux: `s` 1 bit, `a`/`b` `[W-1:0]`.
/// - FF: parameterized `#(W, RST)` — d/q `[W-1:0]`, reset literal via param.
fn cell_module(kind: &CellKind) -> String {
    let name = kind.module_key();
    match kind {
        CellKind::Slice { msb, lsb } => format!(
            "module {name} #(parameter W = 1)(input [W-1:0] a, output [{}-1:0] y);\n  assign y = a[{}:{}];\nendmodule",
            msb - lsb + 1, msb, lsb
        ),
        CellKind::Mux => {
            "module _MUX2 #(parameter W = 1)(input s, input [W-1:0] a, input [W-1:0] b, output [W-1:0] y);\n  assign y = s ? a : b;\nendmodule"
                .into()
        }
        CellKind::Dff => {
            "module DFF #(parameter W = 1)(input c, input [W-1:0] d, output reg [W-1:0] q);\n  always_ff @(posedge c) q <= d;\nendmodule"
                .into()
        }
        CellKind::DffE => {
            "module DFFE #(parameter W = 1)(input c, input ce, input [W-1:0] d, output reg [W-1:0] q);\n  always_ff @(posedge c) if (ce) q <= d;\nendmodule"
                .into()
        }
        CellKind::DffR { reset_value: _, polarity, r#async } => {
            let (edge, cond) = reset_cond(*polarity, *r#async);
            format!(
                "module {name} #(parameter W = 1, parameter RST = 0)(input c, input r, input [W-1:0] d, output reg [W-1:0] q);\n  always_ff @(posedge c{edge}) if ({cond}) q <= RST; else q <= d;\nendmodule",
                edge = edge, cond = cond
            )
        }
        CellKind::DffRE { reset_value: _, polarity, r#async } => {
            let (edge, cond) = reset_cond(*polarity, *r#async);
            format!(
                "module {name} #(parameter W = 1, parameter RST = 0)(input c, input r, input ce, input [W-1:0] d, output reg [W-1:0] q);\n  always_ff @(posedge c{edge}) if ({cond}) q <= RST; else if (ce) q <= d;\nendmodule",
                edge = edge, cond = cond
            )
        }
        CellKind::Lut { init } => lut_module(*init),
        CellKind::Carry4 => {
            "module CARRY4 #(parameter W = 4)(input ci, input [W-1:0] a, input [W-1:0] b, output [W-1:0] s, output co);\n  assign {co, s} = ci + a + b;\nendmodule"
                .into()
        }
        CellKind::Eq
        | CellKind::Ne
        | CellKind::Lt
        | CellKind::Le
        | CellKind::Gt
        | CellKind::Ge
        | CellKind::ReduceAnd
        | CellKind::ReduceOr
        | CellKind::ReduceXor => {
            // Output 1 bit; input operand `[W-1:0]`.
            let (expr, _) = assign_expr(kind);
            let pins = kind.input_pins();
            let ins: Vec<String> = pins.iter().map(|p| format!("input [W-1:0] {p}")).collect();
            format!(
                "module {name} #(parameter W = 1)({}, output y);\n  assign y = {expr};\nendmodule",
                ins.join(", ")
            )
        }
        _ => {
            // Sel bit-vector generik (output = lebar operand): assign fungsional.
            let (expr, _) = assign_expr(kind);
            let ins: Vec<String> = kind
                .input_pins()
                .iter()
                .map(|p| format!("input [W-1:0] {p}"))
                .collect();
            format!(
                "module {name} #(parameter W = 1)({}, output [W-1:0] y);\n  assign y = {expr};\nendmodule",
                ins.join(", ")
            )
        }
    }
}

/// Ekspresi assign fungsional untuk sel kombinasional generik.
fn assign_expr(kind: &CellKind) -> (String, ()) {
    match kind {
        CellKind::And => ("a & b".into(), ()),
        CellKind::Or => ("a | b".into(), ()),
        CellKind::Xor => ("a ^ b".into(), ()),
        CellKind::Not => ("~a".into(), ()),
        CellKind::Mux => ("s ? a : b".into(), ()),
        CellKind::Add => ("a + b".into(), ()),
        CellKind::Sub => ("a - b".into(), ()),
        CellKind::Mul => ("a * b".into(), ()),
        CellKind::Div => ("a / b".into(), ()),
        CellKind::Mod => ("a % b".into(), ()),
        CellKind::Shl => ("a << b".into(), ()),
        CellKind::Shr => ("a >> b".into(), ()),
        CellKind::Sar => ("$signed(a) >>> b".into(), ()),
        CellKind::Eq => ("a == b".into(), ()),
        CellKind::Ne => ("a != b".into(), ()),
        CellKind::Lt => ("a < b".into(), ()),
        CellKind::Le => ("a <= b".into(), ()),
        CellKind::Gt => ("a > b".into(), ()),
        CellKind::Ge => ("a >= b".into(), ()),
        CellKind::ReduceAnd => ("&a".into(), ()),
        CellKind::ReduceOr => ("|a".into(), ()),
        CellKind::ReduceXor => ("^a".into(), ()),
        _ => ("a".into(), ()),
    }
}

/// Kondisi reset (`edge` tambahan + kondisi) dari polarity/async.
fn reset_cond(polarity: bool, r#async: bool) -> (String, String) {
    if r#async {
        if polarity {
            (" or posedge r".into(), "r".into())
        } else {
            (" or negedge r".into(), "!r".into())
        }
    } else if polarity {
        (String::new(), "r".into())
    } else {
        (String::new(), "!r".into())
    }
}

/// Modul LUT6 (phase 4) — truth table `init` 64-bit di-unroll jadi case.
///
/// Index parameter (array `INIT[addr]`) TIDAK bisa — index harus konstanta.
/// Jadi 64 baris case, bit `init[a]` = output untuk addr `{i5,i4,i3,i2,i1,i0}`.
/// Input yang tidak terpakai di-tie `1'b0` oleh mapper → addr tinggi selalu 0,
/// baris di atas `2^K` tidak pernah aktif.
fn lut_module(init: u64) -> String {
    let mut rows = Vec::with_capacity(64);
    for a in 0u64..64 {
        let bit = (init >> a) & 1;
        rows.push(format!("      6'd{}: o = 1'b{};", a, bit));
    }
    format!(
        "module LUT6_{:x}(input i0, input i1, input i2, input i3, input i4, input i5, output o);\n  always_comb begin\n    case ({{i5, i4, i3, i2, i1, i0}})\n{}\n      default: o = 1'b0;\n    endcase\n  end\nendmodule",
        init,
        rows.join("\n")
    )
}

/// Literal konstanta lebar `w`.
pub fn const_lit(w: usize, v: u64) -> String {
    format!("{}'h{:x}", w.max(1), v)
}

/// Instansiasi sel biasa (`<name> #(W, RST) uN (.pin(net), ...);`).
fn emit_instance(s: &mut String, c: &CellInstance, nl: &Netlist) {
    let mut line = format!("  {} {}", c.kind.module_key(), c.name.as_str());
    // Parameter: W = lebar operand (in_width) — Slice juga butuh W (lebar
    // operand penuh; module_key SLICE_{msb}_{lsb} hanya membedakan potongan,
    // bukan lebar sumber). Tanpa W, input `[W-1:0] a` default 1-bit → potongan
    // dari operand lebar ter-truncate ke bit 0. RST hanya untuk FF ber-reset.
    // Guard `max(1)`: node tanpa input (degenerate) tidak menghasilkan `.W(0)`
    // → `input [-1:0] a` invalid.
    // LUT6: modul fixed-width (6 input, 1 output) — tanpa W.
    let mut params: Vec<String> = Vec::new();
    if !matches!(c.kind, CellKind::Lut { .. }) {
        params.push(format!(".W({})", c.in_width.max(1)));
    }
    if let CellKind::DffR { reset_value, .. } | CellKind::DffRE { reset_value, .. } = &c.kind {
        params.push(format!(".RST({})", reset_value));
    }
    if !params.is_empty() {
        line.push_str(&format!(" #({})", params.join(", ")));
    }
    line.push(' ');
    let mut conns = Vec::new();
    for pin in &c.inputs {
        // Selalu referensi net (konstanta sudah jadi wire + assign di top).
        // Bit-select `.i0(a[3])` dipakai LUT/carry saat koneksi ke bit tertentu.
        conns.push(format!(".{}({})", pin.pin, net_ref(&nl, pin)));
    }
    for pin in &c.outputs {
        conns.push(format!(".{}({})", pin.pin, net_ref(&nl, pin)));
    }
    // Koneksi port COMma-separated `(.a(net), .b(net))` — engine Maria hanya
    // mendukung bentuk ini (bentuk space-separated `.a(net) .b(net)` membuat
    // instance di-elaborasi salah: proses always_ff di dalam modul sel hilang
    // → FF tidak pernah berdetak).
    line.push('(');
    line.push_str(&conns.join(", "));
    line.push(')');
    line.push(';');
    let _ = writeln!(s, "{line}");
}

/// Referensi net di koneksi pin: `name` atau `name[bit]` (LUT/carry bit-select).
fn net_ref(nl: &Netlist, pin: &crate::cell::PinConn) -> String {
    let name = nl.nets[pin.net].name.as_str();
    match pin.bit {
        Some(b) => format!("{}[{}]", name, b),
        None => name.to_string(),
    }
}

/// Concat/Buffer di-emit sebagai assign langsung (bukan modul).
fn emit_inline_assign(s: &mut String, c: &CellInstance, nl: &Netlist) {
    let out = &nl.nets[c.outputs[0].net];
    match &c.kind {
        CellKind::Buffer => {
            let inp = &nl.nets[c.inputs[0].net];
            // Referensi net (konstanta = wire + assign di top).
            let _ = writeln!(s, "  assign {} = {};", out.name.as_str(), inp.name.as_str());
        }
        CellKind::Concat => {
            let parts: Vec<String> = c
                .inputs
                .iter()
                .map(|pin| nl.nets[pin.net].name.as_str().to_string())
                .collect();
            let _ = writeln!(
                s,
                "  assign {} = {{{}}};",
                out.name.as_str(),
                parts.join(", ")
            );
        }
        _ => {}
    }
}

/// Emisi `.mvnet` (teks deterministik — port/inst/net).
pub fn emit_mvnet(nl: &Netlist) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "// Generated by maria synth — generic netlist (SYNTHESIS.md §13)"
    );
    let _ = writeln!(s, "device: generic");
    let _ = writeln!(s, "top: {}", nl.name.as_str());
    let _ = writeln!(s);

    for p in &nl.ports {
        let _ = writeln!(
            s,
            "port {:<20} {:<6} [{}:0]",
            p.name.as_str(),
            p.dir.name(),
            p.width.saturating_sub(1)
        );
    }
    if !nl.ports.is_empty() {
        let _ = writeln!(s);
    }
    for c in &nl.cells {
        let mut line = format!("inst {:<20} {}", c.name.as_str(), c.kind.cell_name());
        for pin in &c.inputs {
            let _ = write!(line, " .{}({})", pin.pin, net_ref(nl, pin));
        }
        for pin in &c.outputs {
            let _ = write!(line, " .{}({})", pin.pin, net_ref(nl, pin));
        }
        line.push('\n');
        let _ = s.write_str(&line);
    }
    if !nl.cells.is_empty() {
        let _ = writeln!(s);
    }
    for net in &nl.nets {
        let driver = match &net.driver {
            Some(d) => format!("{}.{}", nl.cells[d.cell].name.as_str(), d.pin),
            None => "-".into(),
        };
        let loads: Vec<String> = net
            .loads
            .iter()
            .map(|l| format!("{}.{}", nl.cells[l.cell].name.as_str(), l.pin))
            .collect();
        let flags: Vec<&str> = {
            let mut f = Vec::new();
            if net.is_clock {
                f.push("clock");
            }
            if net.is_reset {
                f.push("reset");
            }
            if net.is_io {
                f.push("io");
            }
            if net.const_value.is_some() {
                f.push("const");
            }
            f
        };
        let flag_str = if flags.is_empty() {
            String::new()
        } else {
            format!(" ({})", flags.join(","))
        };
        let _ = writeln!(
            s,
            "net {:<24} [{}:0] driver={} loads=[{}]{}",
            net.name.as_str(),
            net.width.saturating_sub(1),
            driver,
            loads.join(","),
            flag_str
        );
    }
    s
}

/// Ringkasan netlist untuk output tool.
pub fn emit_summary(nl: &Netlist) -> String {
    let s = crate::graph::stats(nl);
    let mut out = String::new();
    let _ = writeln!(out, "  top module        {}", nl.name.as_str());
    let _ = writeln!(out, "  device            generic (technology-agnostic)");
    let _ = writeln!(out, "  ports             {}", nl.ports.len());
    let _ = writeln!(
        out,
        "  nets              {} (fanout max {})",
        s.net_count, s.max_fanout
    );
    let _ = writeln!(
        out,
        "  cells             {} (comb {}, FF {})",
        s.cell_count, s.comb_cells, s.ff_cells
    );
    let _ = writeln!(out, "  logic level max   {}", s.max_level);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cell::{CellInstance, PinConn};
    use crate::lower::lower_module;
    use maria_core::intern::Symbol;
    use maria_core::LogicVec;
    use maria_sir::{ResetSpec, SirNode, SirNodeKind, SirRegister, SirValue};

    fn counter_sir() -> maria_sir::SirModule {
        let mut m = maria_sir::SirModule::new(Symbol::intern("counter"));
        let _ = m.add_value(SirValue::Port(0)); // 0 clk
        let _ = m.add_value(SirValue::Port(1)); // 1 rst_n
        let _ = m.add_value(SirValue::Reg(0)); // 2 count
        let _ = m.add_value(SirValue::Const(LogicVec::from_u64(1, 8))); // 3
        let n = m.add_node(SirNodeKind::Add, vec![2, 3], 8);
        let _ = m.add_value(SirValue::Node(n)); // 4
        m.registers.push(SirRegister {
            name: Symbol::intern("count"),
            d: 4,
            q: 2,
            clock: 0,
            reset: Some(ResetSpec {
                signal: 1,
                value: LogicVec::from_u64(0, 8),
                polarity: false,
                r#async: true,
            }),
            enable: None,
            width: 8,
        });
        let mk =
            |name: &str, dir: maria_sir::PortDir, value: usize, width: usize| maria_sir::SirPort {
                name: Symbol::intern(name),
                dir,
                width,
                value,
            };
        m.inputs.push(mk("clk", maria_sir::PortDir::Input, 0, 1));
        m.inputs.push(mk("rst_n", maria_sir::PortDir::Input, 1, 1));
        m.outputs
            .push(mk("count", maria_sir::PortDir::Output, 2, 8));
        m
    }

    #[test]
    fn verilog_structural_has_module_and_instance() {
        let nl = lower_module(&counter_sir());
        let v = emit_verilog(&nl);
        assert!(v.contains("module counter(clk, rst_n, count);"));
        assert!(v.contains("module _ADD #(parameter W = 1)"));
        assert!(v.contains("assign y = a + b;"));
        // module_key menyandikan reset: DFFR_r0_al_a (nilai 0, active-low, async).
        assert!(v.contains("DFFR_r0_al_a ff_count #(.W(8), .RST(0))"));
        assert!(v.contains("always_ff @(posedge c or negedge r)"));
        // Koneksi port COMma-separated `(.a(net), .b(net))` — engine Maria
        // hanya mengelaborasi bentuk ini; space-separated membuat always_ff
        // di module sel hilang → FF tidak pernah berdetak (regresi fase 3).
        assert!(v.contains("(.c(clk), .r(rst_n), .d("));
        assert!(v.contains(", .q(count))"));
        assert!(!v.contains(" .c(clk) .r("), "koneksi harus comma-separated");
        assert!(v.contains("endmodule"));
    }

    #[test]
    fn mvnet_and_summary() {
        let nl = lower_module(&counter_sir());
        let m = emit_mvnet(&nl);
        assert!(m.contains("device: generic"));
        assert!(m.contains("top: counter"));
        assert!(m.contains("inst ff_count") && m.contains("DFFR"));
        assert!(m.contains("inst u0") && m.contains("_ADD"));
        let sum = emit_summary(&nl);
        assert!(sum.contains("FF"));
    }
}
