// ─────────────────────────────────────────────────────────────
// Generated by maria mgen — DO NOT EDIT
// Sumber    : my_test.mv
// Perintah  : maria mgen my_test.mv
// ─────────────────────────────────────────────────────────────

`ifndef MY_TEST_SVH
`define MY_TEST_SVH

`endif
