//! Emisi netlist → format teks `.mvnet` (SYNTHESIS.md §3.1).
//!
//! Format teks deterministik (bisa di-commit, di-diff, dibaca manusia):
//! header → device/top → port → inst → net.

use std::fmt::Write;

use crate::netlist::{Instance, Netlist};

/// Emisi `.mvnet` penuh.
pub fn emit_mvnet(nl: &Netlist, version: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "// Generated by maria msynth {} — DO NOT EDIT", version);
    let _ = writeln!(s, "device: {}", nl.device.name());
    let _ = writeln!(s, "top: {}", nl.name.as_str());
    let _ = writeln!(s);

    // ── Port ──
    for p in &nl.ports {
        let _ = writeln!(
            s,
            "port {:<20} {:<6} [{}:0]",
            p.name.as_str(),
            p.dir.name(),
            p.width.saturating_sub(1)
        );
    }
    if !nl.ports.is_empty() {
        let _ = writeln!(s);
    }

    // ── Instance ──
    for inst in &nl.instances {
        emit_instance(&mut s, inst, nl);
    }
    if !nl.instances.is_empty() {
        let _ = writeln!(s);
    }

    // ── Net ──
    for net in &nl.nets {
        let driver = match net.driver {
            Some(i) => nl.instances[i].name.as_str().to_string(),
            None => "-".into(),
        };
        let loads: Vec<String> = net
            .loads
            .iter()
            .map(|l| nl.instances[*l].name.as_str().to_string())
            .collect();
        let flags: Vec<&str> = {
            let mut f = Vec::new();
            if net.is_clock {
                f.push("clock");
            }
            if net.is_reset {
                f.push("reset");
            }
            if net.is_io {
                f.push("io");
            }
            f
        };
        let flag_str = if flags.is_empty() {
            String::new()
        } else {
            format!(" ({})", flags.join(","))
        };
        let _ = writeln!(
            s,
            "net {:<24} [{}:0] driver={} loads=[{}]{}",
            net.name.as_str(),
            net.width.saturating_sub(1),
            driver,
            loads.join(","),
            flag_str
        );
    }

    s
}

fn emit_instance(s: &mut String, inst: &Instance, nl: &Netlist) {
    let mut line = format!("inst {:<20} {}", inst.name.as_str(), inst.kind.cell_name());
    for pin in &inst.inputs {
        let _ = write!(line, " .{}({})", pin.pin, nl.nets[pin.net].name.as_str());
    }
    for pin in &inst.outputs {
        let _ = write!(line, " .{}({})", pin.pin, nl.nets[pin.net].name.as_str());
    }
    if let Some((r, c, _)) = inst.loc {
        let _ = write!(line, " @({},{})", r, c);
    }
    line.push('\n');
    let _ = s.write_str(&line);
}

/// Emisi ringkas statistik netlist (untuk output tool).
pub fn emit_summary(nl: &Netlist) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "  top module        {}", nl.name.as_str());
    let _ = writeln!(s, "  device            {}", nl.device.name());
    let _ = writeln!(s, "  ports             {}", nl.ports.len());
    let _ = writeln!(s, "  nets              {}", nl.nets.len());
    let _ = writeln!(s, "  instances         {}", nl.instances.len());
    let _ = writeln!(
        s,
        "  ── FF {:>4}  LUT(est) {:>5}  CARRY4 {:>4}  BRAM {:>3}  ROM {:>3}  DSP {:>3}",
        nl.stats.ff_count,
        nl.stats.lut_count,
        nl.stats.carry4_count,
        nl.stats.bram_count,
        nl.stats.rom_count,
        nl.stats.dsp_count
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::netlist::{CellKind, DeviceKind, Port, PortDir};
    use maria_core::intern::Symbol;

    fn small_netlist() -> Netlist {
        let mut nl = Netlist::new(Symbol::intern("top"), DeviceKind::FpgaX7);
        let clk = nl.add_net(Symbol::intern("clk"), 1);
        let d = nl.add_net(Symbol::intern("d"), 1);
        let q = nl.add_net(Symbol::intern("q"), 1);
        let ff = crate::netlist::ff_instance(
            Symbol::intern("u0"),
            CellKind::DffR { reset_value: 0 },
            clk,
            d,
            q,
            None,
            None,
        );
        nl.add_instance(ff);
        nl.nets[clk].is_clock = true;
        nl.ports.push(Port {
            name: Symbol::intern("clk"),
            dir: PortDir::Input,
            width: 1,
        });
        nl
    }

    #[test]
    fn mvnet_emits_header_and_sections() {
        let nl = small_netlist();
        let s = emit_mvnet(&nl, "v0.1");
        assert!(s.starts_with("// Generated by maria msynth"));
        assert!(s.contains("device: fpga-x7"));
        assert!(s.contains("top: top"));
        assert!(s.contains("port clk"));
        assert!(s.contains("inst u0"));
        assert!(s.contains("net clk"));
        assert!(s.contains("(clock)"));
        // Nama net asli dipakai di instance.
        assert!(s.contains(".d(d)"));
        assert!(s.contains(".q(q)"));
    }

    #[test]
    fn emit_is_deterministic() {
        let a = emit_mvnet(&small_netlist(), "v0.1");
        let b = emit_mvnet(&small_netlist(), "v0.1");
        assert_eq!(a, b);
    }
}
