[package]
name = "maria-fuzz"
version = "0.1.0"
edition = "2021"
description = "maria  fuzzer internal (dev-only) — bukan CLI user"

[lib]
name = "maria_fuzz"
path = "src/lib.rs"

[[bin]]
name = "maria-fuzz"
path = "src/main.rs"
required-features = ["dev"]

[features]
dev = []

