//! Maria HDL (.mv) — Codegen.
//! Emitter SystemVerilog: AST (src/mv/ast.rs) → `.sv` + `.svh`.
//! 1 file = 1 tanggung jawab: hanya emisi SV (output indah & deterministik).
//!
//! Konvensi output (MARIA-HDL.md §10):
//! - `.svh`: header + include guard + package + typedef + interface (definisi bersama)
//! - `.sv` : header + `include `.svh`` + module + program + class + function/task
//! - Header `// Generated by maria mgen — DO NOT EDIT` + perintah regenerate

use crate::ast::*;

/// Hasil codegen: (sv, svh).
#[derive(Debug, Clone)]
pub struct GenOutput {
    pub sv: String,
    pub svh: String,
}

/// Generate `.sv` + `.svh` dari `MvFile` (konteks satu file).
/// `base` = nama file tanpa ekstensi (mis. `counter` dari `counter.mv`).
/// Interface yang didefinisikan di file ini ikut dikenal (port interface
/// di-emit tanpa arah).
pub fn generate(file: &MvFile, base: &str) -> GenOutput {
    let ifaces: Vec<&str> = file.interfaces.iter().map(|i| i.name.as_str()).collect();
    generate_with_ifaces(file, base, &ifaces)
}

/// Generate dgn nama interface dari KONTEKS GABUNGAN (F26): port module
/// bertipe interface yang didefinisikan di FILE LAIN juga di-emit tanpa
/// arah (`bus b`) — konsisten dengan `check_many` yang memakai konteks
/// gabungan. `iface_names` = nama interface dari semua file dalam batch;
/// interface tetap di-emit ke `.svh` hanya dari definisinya sendiri
/// (`file.interfaces`). `generate` (satu file) memanggil ini dgn daftar kosong.
pub fn generate_with_ifaces(file: &MvFile, base: &str, iface_names: &[&str]) -> GenOutput {
    let header = header(base);
    let svh = generate_svh(file, base, &header);
    let sv = generate_sv(file, base, &header, iface_names);
    GenOutput { sv, svh }
}

// ── Header ──

fn header(base: &str) -> String {
    let line = "// ─────────────────────────────────────────────────────────────";
    format!(
        "{line}\n// Generated by maria mgen — DO NOT EDIT\n// Sumber    : {base}.mv\n// Perintah  : maria mgen {base}.mv\n{line}\n"
    )
}

// ── .svh ──

/// Emit `.svh` HANYA jika file punya definisi bersama (package atau typedef
/// level file) yang perlu di-include oleh `.sv`. File tanpa keduanya tidak
/// membutuhkan `.svh` sama sekali — hasilnya kosong, dan `mgen` tidak menulis
/// file tersebut (lihat src/tools/gen.rs).
fn generate_svh(file: &MvFile, base: &str, header: &str) -> String {
    // Definisi bersama = typedef level file + package + interface (F26).
    let has_shared = !file.typedefs.is_empty() || !file.packages.is_empty() || !file.interfaces.is_empty();
    if !has_shared {
        return String::new();
    }
    let guard = format!("{}_SVH", base.to_uppercase());
    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    out.push_str(&format!("`ifndef {guard}\n`define {guard}\n"));

    // Typedef level file → $unit (terlihat semua module yang include)
    for td in &file.typedefs {
        out.push('\n');
        emit_typedef(&mut out, 0, td);
    }
    // Package
    for pkg in &file.packages {
        out.push('\n');
        emit_package(&mut out, 0, pkg);
    }
    // Interface (MARIA-HDL.md §6.10) — definisi bersama, di-emit ke .svh
    for ifc in &file.interfaces {
        out.push('\n');
        emit_interface(&mut out, 0, ifc);
    }

    out.push('\n');
    out.push_str(&format!("`endif\n"));
    out
}

/// Emit interface SV: `interface axi_lite; ... endinterface`.
/// Port (`in/out`) & `sig` sama-sama jadi deklarasi signal; modport
/// menamai subset signal dengan arah (MARIA-HDL.md §6.10).
fn emit_interface(out: &mut String, indent: usize, ifc: &Interface) {
    line(out, indent, &format!("interface {};", ifc.name));
    // Port interface → deklarasi signal (arah tidak di-emit di level ini;
    // hanya modport yang membawa arah).
    for p in &ifc.ports {
        for n in &p.names {
            line(out, indent + 1, &format!("{} {n};", emit_type(&p.ty)));
        }
    }
    for (names, ty, ..) in &ifc.sigs {
        line(out, indent + 1, &format!("{} {};", emit_type(ty), names.join(", ")));
    }
    for mp in &ifc.modports {
        let parts: Vec<String> = mp
            .dirs
            .iter()
            .map(|(dir, names)| {
                let d = match dir {
                    Dir::In => "input",
                    Dir::Out => "output",
                    Dir::Inout => "inout",
                };
                format!("{d} {}", names.join(", "))
            })
            .collect();
        line(out, indent + 1, &format!("modport {} ({});", mp.name, parts.join(", ")));
    }
    line(out, indent, "endinterface");
}

fn emit_package(out: &mut String, indent: usize, pkg: &Package) {
    line(out, indent, &format!("package {};", pkg.name));
    for td in &pkg.typedefs {
        emit_typedef(out, indent + 1, td);
    }
    for (name, ty, value) in &pkg.consts {
        let ty_s = ty.as_ref().map(|t| format!("{} ", emit_type(t))).unwrap_or_default();
        line(out, indent + 1, &format!("localparam {ty_s}{name} = {};", emit_expr(value)));
    }
    line(out, indent, "endpackage");
}

fn emit_typedef(out: &mut String, indent: usize, td: &Typedef) {
    match td {
        Typedef::Alias { name, ty, .. } => {
            line(out, indent, &format!("typedef {} {name};", emit_type(ty)));
        }
        Typedef::Struct { name, packed, fields, .. } => {
            let pk = if *packed { " packed" } else { "" };
            line(out, indent, &format!("typedef struct{pk} {{"));
            for f in fields {
                let names = f.names.join(", ");
                let ty_s = pad_type(emit_type(&f.ty));
                line(out, indent + 1, &format!("{ty_s}{names};"));
            }
            line(out, indent, &format!("}} {name};"));
        }
        Typedef::Union { name, packed, fields, .. } => {
            let pk = if *packed { " packed" } else { "" };
            line(out, indent, &format!("typedef union{pk} {{"));
            for f in fields {
                let names = f.names.join(", ");
                let ty_s = pad_type(emit_type(&f.ty));
                line(out, indent + 1, &format!("{ty_s}{names};"));
            }
            line(out, indent, &format!("}} {name};"));
        }
        Typedef::Enum { name, width, members, .. } => {
            let w = match width {
                // `enum(N)` = N bit → `[N-1:0]`
                Some(Expr::Int(n)) => format!("{}", n - 1),
                Some(w) => format!("{} - 1", emit_expr(w)),
                None => format!("{}", enum_width(members.len())),
            };
            let members_s: Vec<String> = members
                .iter()
                .map(|m| match &m.value {
                    Some(v) => format!("{} = {}", m.name, emit_expr(v)),
                    None => m.name.clone(),
                })
                .collect();
            let joined = members_s.join(", ");
            line(out, indent, &format!("typedef enum logic [{w}:0] {{ {joined} }} {name};"));
        }
    }
}

/// Lebar enum implisit: clog2(n), minimal 1.
fn enum_width(n: usize) -> i64 {
    if n <= 2 {
        1
    } else {
        ((n - 1) as f64).log2().ceil() as i64
    }
}

// ── .sv ──

fn generate_sv(file: &MvFile, base: &str, header: &str, iface_names: &[&str]) -> String {
    // F30 fix: file yang hanya berisi definisi bersama (package/typedef/
    // interface) tanpa module/program/class/func/task tidak menghasilkan
    // konten fungsional — kembalikan kosong agar `mgen` tidak menulis .sv
    // yang isinya hanya header + `include` (konsisten dengan skip .svh
    // kosong di src/tools/gen.rs). File ber-module tetap punya include.
    let has_content = !file.modules.is_empty()
        || !file.programs.is_empty()
        || !file.classes.is_empty()
        || !file.funcs.is_empty()
        || !file.tasks.is_empty();
    if !has_content {
        return String::new();
    }

    let mut out = String::new();
    out.push_str(header);
    out.push('\n');

    let has_shared = !file.typedefs.is_empty() || !file.packages.is_empty() || !file.interfaces.is_empty();
    if has_shared {
        out.push_str(&format!("`include \"{base}.svh\"\n"));
    }

    // Nama interface — port module bertipe interface di-emit TANPA arah
    // (`axi_lite axi_if`, bukan `input axi_lite axi_if`) — F26. Daftar bisa
    // dari konteks gabungan (multi-file, F26 fix review) atau file ini saja.
    for m in &file.modules {
        out.push('\n');
        emit_module_kw(&mut out, m, "module", iface_names);
    }
    // `program name { ... }` (MARIA-HDL.md §7.3) — testbench program
    for p in &file.programs {
        out.push('\n');
        emit_module_kw(&mut out, p, "program", iface_names);
    }
    // `class name [extends base] { ... }` (MARIA-HDL.md §8)
    for c in &file.classes {
        out.push('\n');
        emit_class(&mut out, c);
    }
    for f in &file.funcs {
        out.push('\n');
        emit_func(&mut out, f);
    }
    for t in &file.tasks {
        out.push('\n');
        emit_task(&mut out, t);
    }
    out
}

/// Emit `module` atau `program` (testbench, MARIA-HDL.md §7.3) — struktur
/// badan sama, hanya keyword pembuka/penutup yang beda.
/// `iface_names` = nama interface di file ini; port bertipe interface
/// di-emit sebagai `iface port` (tanpa arah) — F26.
fn emit_module_kw(out: &mut String, m: &Module, kw: &str, iface_names: &[&str]) {
    // header module
    let mut head = format!("{kw} {} ", m.name);
    if !m.params.is_empty() {
        head.push_str("#(\n");
        let params: Vec<String> = m
            .params
            .iter()
            .map(|p| {
                let ty = if p.type_default.is_some()
                    || matches!(&p.ty, Some(MvType::Named(s, ..)) if s == "type")
                {
                    // F32: type param (marker `T : type = ...` ATAU bentuk kata
                    // kunci `type T = ...` — ty=None, type_default terisi).
                    // Default adalah TIPE (`parameter type T = logic [7:0]`).
                    format!("parameter type {} = {}", p.name, p.type_default.as_ref().map(emit_type).unwrap_or_default())
                } else if let Some(t) = &p.ty {
                    format!("parameter {} {} = {}", emit_type(t), p.name, p.default.as_ref().map(emit_expr).unwrap_or_default())
                } else {
                    format!("parameter {} = {}", p.name, p.default.as_ref().map(emit_expr).unwrap_or_default())
                };
                format!("    {ty}")
            })
            .collect();
        head.push_str(&params.join(",\n"));
        head.push_str("\n) ");
    }
    head.push_str("(\n");
    // ports
    let mut port_lines: Vec<String> = Vec::new();
    for item in &m.items {
        if let MItem::Port(p) = item {
            let ty = emit_type(&p.ty);
            let is_iface = matches!(&p.ty, MvType::Named(n, ..) if iface_names.contains(&n.as_str()));
            for n in &p.names {
                if is_iface {
                    // Port interface: `axi_lite axi_if` — tanpa arah (F26)
                    port_lines.push(format!("    {ty} {n}"));
                } else {
                    let dir = match p.dir {
                        Dir::In => "input",
                        Dir::Out => "output",
                        Dir::Inout => "inout",
                    };
                    // Rata kanan arah port: `input  bit clk` / `output logic [..] count`
                    port_lines.push(format!("    {dir:<7}{ty} {n}"));
                }
            }
        }
    }
    head.push_str(&port_lines.join(",\n"));
    head.push_str("\n);");
    line(out, 0, &head);

    // Kumpulkan nama port (agar sig/reg dengan nama port tidak dideklarasi ulang)
    let port_names: Vec<String> = m
        .items
        .iter()
        .filter_map(|i| match i {
            MItem::Port(p) => Some(p.names.clone()),
            _ => None,
        })
        .flatten()
        .collect();

    // deklarasi + blok + instansiasi — pertahankan urutan penulisan
    for item in &m.items {
        match item {
            MItem::Port(_) => {}
            MItem::Sig { names, ty, init, .. } => {
                let fresh: Vec<String> = names.iter().filter(|n| !port_names.contains(n)).cloned().collect();
                if !fresh.is_empty() {
                    // F28: `sig x : iface` = instance interface → emit dgn paren
                    // kosong (`axi_lite bus();`) — bukan deklarasi vif variabel
                    // (`axi_lite bus;` di-parse SV sbg virtual interface var).
                    let is_iface = match ty {
                        MvType::Named(n, ..) => iface_names.contains(&n.as_str()),
                        _ => false,
                    };
                    if is_iface {
                        for nm in &fresh {
                            line(out, 1, &format!("{} {}();", emit_type(ty), nm));
                        }
                    } else {
                        let init_s = init.as_ref().map(|e| format!(" = {}", emit_expr(e))).unwrap_or_default();
                        line(out, 1, &format!("{} {}{};", emit_type(ty), fresh.join(", "), init_s));
                    }
                }
            }
            MItem::Reg { names, ty, init, .. } => {
                let fresh: Vec<String> = names.iter().filter(|n| !port_names.contains(n)).cloned().collect();
                if !fresh.is_empty() {
                    let init_s = init.as_ref().map(|e| format!(" = {}", emit_expr(e))).unwrap_or_default();
                    line(out, 1, &format!("{} {}{};", emit_type(ty), fresh.join(", "), init_s));
                }
            }
            MItem::Const { name, ty, value, .. } => {
                let ty_s = ty.as_ref().map(|t| format!("{} ", emit_type(t))).unwrap_or_default();
                line(out, 1, &format!("localparam {ty_s}{name} = {};", emit_expr(value)));
            }
            MItem::Use { pkg, item } => {
                line(out, 1, &format!("import {pkg}::{item};"));
            }
            MItem::Seq(spec, body) => {
                line(out, 0, "");
                line(out, 1, "// ── logika sekuensial ──");
                emit_seq(out, 1, spec, body);
            }
            MItem::Comb(body) => {
                line(out, 0, "");
                line(out, 1, "// ── logika kombinasional ──");
                line(out, 1, "always_comb begin");
                emit_body(out, 2, body);
                line(out, 1, "end");
            }
            MItem::Always(body) => {
                line(out, 0, "");
                line(out, 1, "// ── always ──");
                line(out, 1, "always begin");
                emit_body(out, 2, body);
                line(out, 1, "end");
            }
            MItem::Latch(body) => {
                line(out, 0, "");
                line(out, 1, "// ── latch ──");
                line(out, 1, "always_latch begin");
                emit_body(out, 2, body);
                line(out, 1, "end");
            }
            MItem::Initial(body) => {
                line(out, 0, "");
                line(out, 1, "// ── initial ──");
                line(out, 1, "initial begin");
                emit_body(out, 2, body);
                line(out, 1, "end");
            }
            MItem::Final(body) => {
                line(out, 0, "");
                line(out, 1, "// ── final ──");
                line(out, 1, "final begin");
                emit_body(out, 2, body);
                line(out, 1, "end");
            }
            MItem::Inst { module, name, dims, params, conns, .. } => {
                line(out, 0, "");
                emit_inst(out, 1, module, name, dims, params, conns);
            }
            MItem::GenFor { var, from, to, body } => {
                line(out, 0, "");
                line(out, 0, "generate");
                line(
                    out,
                    1,
                    &format!("for (genvar {var} = {}; {var} < {}; {var} = {var} + 1) begin : gen_{var}", emit_expr(from), emit_expr(to)),
                );
                for item in body {
                    emit_module_item_at(out, 2, item, iface_names);
                }
                line(out, 1, "end");
                line(out, 0, "endgenerate");
            }
            MItem::GenIf { cond, then, els } => {
                line(out, 0, "");
                line(out, 0, "generate");
                line(out, 1, &format!("if ({}) begin : gen_cond", emit_expr(cond)));
                for item in then {
                    emit_module_item_at(out, 2, item, iface_names);
                }
                line(out, 1, "end");
                if !els.is_empty() {
                    line(out, 1, "else begin : gen_cond_else");
                    for item in els {
                        emit_module_item_at(out, 2, item, iface_names);
                    }
                    line(out, 1, "end");
                }
                line(out, 0, "endgenerate");
            }
            MItem::Func(f) => emit_func(out, f),
            MItem::Task(t) => emit_task(out, t),
        }
    }
    line(out, 0, &format!("end{kw}"));
}

/// Emit satu item module di indentasi tertentu — dipakai di level module
/// maupun di dalam blok generate. Semua item di-emit (Sig/Reg/Const/Use/
/// Func/Task TIDAK boleh di-drop diam-diam — error harus muncul di .mv,
/// bukan hilang dari output SV).
fn emit_module_item_at(out: &mut String, indent: usize, item: &MItem, iface_names: &[&str]) {
    match item {
        MItem::Port(_) => {} // port hanya valid di header module
        MItem::Sig { names, ty, init, .. } => {
            // F28: `sig x : iface` = instance interface (lihat emit_module_kw).
            let is_iface = match ty {
                MvType::Named(n, ..) => iface_names.contains(&n.as_str()),
                _ => false,
            };
            if is_iface {
                for nm in names {
                    line(out, indent, &format!("{} {}();", emit_type(ty), nm));
                }
            } else {
                let init_s = init.as_ref().map(|e| format!(" = {}", emit_expr(e))).unwrap_or_default();
                line(out, indent, &format!("{} {}{};", emit_type(ty), names.join(", "), init_s));
            }
        }
        MItem::Reg { names, ty, init, .. } => {
            let init_s = init.as_ref().map(|e| format!(" = {}", emit_expr(e))).unwrap_or_default();
            line(out, indent, &format!("{} {}{};", emit_type(ty), names.join(", "), init_s));
        }
        MItem::Const { name, ty, value, .. } => {
            let ty_s = ty.as_ref().map(|t| format!("{} ", emit_type(t))).unwrap_or_default();
            line(out, indent, &format!("localparam {ty_s}{name} = {};", emit_expr(value)));
        }
        MItem::Use { pkg, item } => {
            line(out, indent, &format!("import {pkg}::{item};"));
        }
        MItem::Seq(spec, body) => emit_seq(out, indent, spec, body),
        MItem::Comb(body) => {
            line(out, indent, "always_comb begin");
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        MItem::Always(body) => {
            line(out, indent, "always begin");
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        MItem::Latch(body) => {
            line(out, indent, "always_latch begin");
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        MItem::Initial(body) => {
            line(out, indent, "initial begin");
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        MItem::Final(body) => {
            line(out, indent, "final begin");
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        MItem::Inst { module, name, dims, params, conns, .. } => {
            emit_inst(out, indent, module, name, dims, params, conns);
        }
        MItem::GenFor { var, from, to, body } => {
            line(out, indent, "generate");
            line(
                out,
                indent + 1,
                &format!("for (genvar {var} = {}; {var} < {}; {var} = {var} + 1) begin : gen_{var}", emit_expr(from), emit_expr(to)),
            );
            for i in body {
                emit_module_item_at(out, indent + 2, i, iface_names);
            }
            line(out, indent + 1, "end");
            line(out, indent, "endgenerate");
        }
        MItem::GenIf { cond, then, els } => {
            line(out, indent, "generate");
            line(out, indent + 1, &format!("if ({}) begin : gen_cond", emit_expr(cond)));
            for i in then {
                emit_module_item_at(out, indent + 2, i, iface_names);
            }
            line(out, indent + 1, "end");
            if !els.is_empty() {
                line(out, indent + 1, "else begin : gen_cond_else");
                for i in els {
                    emit_module_item_at(out, indent + 2, i, iface_names);
                }
                line(out, indent + 1, "end");
            }
            line(out, indent, "endgenerate");
        }
        MItem::Func(f) => emit_func(out, f),
        MItem::Task(t) => emit_task(out, t),
    }
}

fn emit_seq(out: &mut String, indent: usize, spec: &SeqSpec, body: &Stmt) {
    let edge = if spec.neg_edge { "negedge" } else { "posedge" };
    // Bangun `@(posedge clk [or negedge rst_n])` — reset DI DALAM kurung.
    let mut event = format!("@({edge} {}", spec.clk);
    if let Some((rname, active_low, sync)) = &spec.reset {
        if !sync {
            let re = if *active_low { "negedge" } else { "posedge" };
            event.push_str(&format!(" or {re} {rname}"));
        }
    }
    event.push(')');
    line(out, indent, &format!("always_ff {event} begin"));
    emit_body(out, indent + 1, body);
    line(out, indent, "end");
}

fn emit_inst(
    out: &mut String,
    indent: usize,
    module: &str,
    name: &str,
    dims: &Option<Expr>,
    params: &[(String, Expr)],
    conns: &[Conn],
) {
    let dims_s = dims.as_ref().map(|d| format!("[{}]", emit_expr(d))).unwrap_or_default();
    let mut head = format!("{module} {name}{dims_s}");
    if !params.is_empty() {
        let ps: Vec<String> = params.iter().map(|(n, e)| format!(".{n}({})", emit_expr(e))).collect();
        head.push_str(&format!(" #({})", ps.join(", ")));
    }
    if conns.is_empty() {
        line(out, indent, &format!("{head};"));
        return;
    }
    // named: rata kiri nama port
    let named: Vec<&Conn> = conns.iter().filter(|c| matches!(c, Conn::Named { .. })).collect();
    let max_len = named
        .iter()
        .map(|c| match c {
            Conn::Named { port, .. } => port.len(),
            _ => 0,
        })
        .max()
        .unwrap_or(0);
    line(out, indent, &format!("{head} ("));
    let n = conns.len();
    for (i, c) in conns.iter().enumerate() {
        // Koma pemisah koneksi — tanpa ini output instansiasi INVALID (bug
        // lama: `.clk (clk)` tanpa `,`; terdeteksi saat tb_counter disimulasi).
        let sep = if i + 1 == n { "" } else { "," };
        match c {
            Conn::Named { port, expr } => {
                let e = expr.as_ref().map(emit_expr).unwrap_or_else(|| port.clone());
                line(out, indent + 1, &format!(".{port}{}({e}){sep}", " ".repeat(max_len - port.len() + 1)));
            }
            Conn::Positional(e) => {
                line(out, indent + 1, &format!("{}({}){sep}", " ".repeat(max_len), emit_expr(e)));
            }
        }
    }
    line(out, indent, ");");
}

fn emit_func(out: &mut String, f: &MFunc) {
    let ret = f.ret.as_ref().map(emit_type).unwrap_or_else(|| "void".into());
    let args = emit_args(&f.args, false);
    line(out, 0, &format!("function {ret} {}({});", f.name, args.join(", ")));
    for s in &f.body {
        emit_stmt(out, 1, s);
    }
    line(out, 0, "endfunction");
}

fn emit_task(out: &mut String, t: &MTask) {
    let args = emit_args(&t.args, true);
    line(out, 0, &format!("task {}({});", t.name, args.join(", ")));
    for s in &t.body {
        emit_stmt(out, 1, s);
    }
    line(out, 0, "endtask");
}

/// Format daftar argumen `(nama, tipe, arah)` — dipakai emit_func/emit_task/
/// emit_class (DRY). `default_inout`: arah default saat tidak ditulis
/// (task → inout; function → input).
fn emit_args(args: &[(String, MvType, Option<Dir>)], default_inout: bool) -> Vec<String> {
    args.iter()
        .map(|(n, t, d)| {
            let dir = match d {
                Some(Dir::In) => "input",
                Some(Dir::Out) => "output",
                Some(Dir::Inout) => "inout",
                None if default_inout => "inout",
                None => "input",
            };
            format!("{dir} {} {n}", emit_type(t))
        })
        .collect()
}

/// Item constraint SV (F12): ekspresi `e;`, `if (c) begin ... end [else
/// begin ... end]`, `solve x before a, b;` — emisi 1:1 dengan sintaks .mv.
fn emit_constraint_items(out: &mut String, indent: usize, items: &[ConstraintItem]) {
    for item in items {
        match item {
            ConstraintItem::Expr(e) => {
                line(out, indent, &format!("{};", emit_expr(e)));
            }
            // Constraint `if` SV memakai `{ }`, BUKAN begin/end (sintaks
            // constraint block, bukan procedural block).
            ConstraintItem::If { cond, then, els } => {
                line(out, indent, &format!("if ({}) {{", emit_expr(cond)));
                emit_constraint_items(out, indent + 1, then);
                if els.is_empty() {
                    line(out, indent, "}");
                } else {
                    line(out, indent, "} else {");
                    emit_constraint_items(out, indent + 1, els);
                    line(out, indent, "}");
                }
            }
            ConstraintItem::Solve { var, before, .. } => {
                line(out, indent, &format!("solve {var} before {};", before.join(", ")));
            }
        }
    }
}

/// Emit class SV (MARIA-HDL.md §8): `class Name extends Base; ... endclass`.
fn emit_class(out: &mut String, c: &MClass) {
    let ext = c.extends.as_ref().map(|b| format!(" extends {b}")).unwrap_or_default();
    line(out, 0, &format!("class {}{};", c.name, ext));

    // field (nama member; padding tipe agar kolom nama rapi)
    for (name, ty, rand) in &c.fields {
        let r = if *rand { "rand " } else { "" };
        line(out, 1, &format!("{r}{} {name};", emit_type(ty)));
    }

    // constraint → `constraint name { items }` (F12: ekspresi/inside/dist,
    // if/else, solve-before — emisi 1:1)
    for (cname, items) in &c.constraints {
        line(out, 0, "");
        line(out, 1, &format!("constraint {cname} {{"));
        emit_constraint_items(out, 2, items);
        line(out, 1, "}");
    }

    // method: function (constructor `new` tanpa tipe return) / task
    for f in &c.funcs {
        line(out, 0, "");
        let ret = if f.name == "new" {
            String::new()
        } else {
            format!("{} ", f.ret.as_ref().map(emit_type).unwrap_or_else(|| "void".into()))
        };
        let args = emit_args(&f.args, false);
        line(out, 1, &format!("function {ret}{}({});", f.name, args.join(", ")));
        for s in &f.body {
            emit_stmt(out, 2, s);
        }
        line(out, 1, "endfunction");
    }
    for t in &c.tasks {
        line(out, 0, "");
        let args = emit_args(&t.args, true);
        line(out, 1, &format!("task {}({});", t.name, args.join(", ")));
        for s in &t.body {
            emit_stmt(out, 2, s);
        }
        line(out, 1, "endtask");
    }
    line(out, 0, "endclass");
}

// ── Statements ──

fn emit_stmt(out: &mut String, indent: usize, stmt: &Stmt) {
    match stmt {
        Stmt::Block(stmts) => {
            line(out, indent, "begin");
            for s in stmts {
                emit_stmt(out, indent + 1, s);
            }
            line(out, indent, "end");
        }
        Stmt::Assign { lhs, rhs, nba, .. } => {
            let op = if *nba { "<=" } else { "=" };
            line(out, indent, &format!("{} {op} {};", emit_expr(lhs), emit_expr(rhs)));
        }
        // F36/F37: compound assignment `lhs += rhs` / increment `lhs++` / `++lhs`.
        Stmt::CompoundAssign { lhs, op, rhs, .. } => {
            line(out, indent, &format!("{} {op} {};", emit_expr(lhs), emit_expr(rhs)));
        }
        Stmt::IncDec { lhs, inc, pre, .. } => {
            let op = if *inc { "++" } else { "--" };
            if *pre {
                // F37: prefix `++lhs`
                line(out, indent, &format!("{}{};", op, emit_expr(lhs)));
            } else {
                // F36: postfix `lhs++`
                line(out, indent, &format!("{}{};", emit_expr(lhs), op));
            }
        }
        Stmt::If { cond, then, els } => {
            line(out, indent, &format!("if ({}) begin", emit_expr(cond)));
            emit_body(out, indent + 1, then);
            emit_else_chain(out, indent, els.as_deref());
        }
        Stmt::Case {
            expr,
            items,
            default,
            qual,
            kind,
        } => {
            // F26: qualifier priority/unique/unique0 + casez/casex.
            let kw = match kind.as_str() {
                "casez" => "casez",
                "casex" => "casex",
                _ => "case",
            };
            let head = match qual {
                Some(q) => format!("{} {}", q, kw),
                None => kw.to_string(),
            };
            line(out, indent, &format!("{} ({})", head, emit_expr(expr)));
            for (vals, body) in items {
                let vs: Vec<String> = vals.iter().map(emit_expr).collect();
                line(out, indent + 1, &format!("{}: begin", vs.join(", ")));
                emit_body(out, indent + 2, body);
                line(out, indent + 1, "end");
            }
            if let Some(d) = default {
                line(out, indent + 1, "default: begin");
                emit_body(out, indent + 2, d);
                line(out, indent + 1, "end");
            }
            line(out, indent, "endcase");
        }
        Stmt::For { var, from, to, body } => {
            line(
                out,
                indent,
                &format!("for (int {var} = {}; {var} < {}; {var} = {var} + 1) begin", emit_expr(from), emit_expr(to)),
            );
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        Stmt::While { cond, body } => {
            line(out, indent, &format!("while ({}) begin", emit_expr(cond)));
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        // F38: `do { ... } while (cond)` — loop post-test.
        Stmt::DoWhile { cond, body } => {
            line(out, indent, "do begin");
            emit_body(out, indent + 1, body);
            line(out, indent, &format!("end while ({});", emit_expr(cond)));
        }
        // F38: event trigger `->ev` → `-> ev;`
        Stmt::EventTrigger(ev) => {
            line(out, indent, &format!("-> {};", emit_expr(ev)));
        }
        // F39: `fork { ... } join[_any|_none]` — tiap branch di-emit sebagai
        // `begin ... end` (parser SV parse_fork_join: tiap `begin/end` = satu
        // proses). Mode join sesuai aslinya.
        Stmt::Fork { branches, join } => {
            line(out, indent, "fork");
            for b in branches {
                line(out, indent + 1, "begin");
                emit_body(out, indent + 2, b);
                line(out, indent + 1, "end");
            }
            let j = match join {
                ForkJoin::Join => "join",
                ForkJoin::JoinAny => "join_any",
                ForkJoin::JoinNone => "join_none",
            };
            line(out, indent, j);
        }
        Stmt::Repeat { count, body } => {
            // Body statement tunggal → satu baris (`repeat (300) @(posedge clk)`)
            if let Some(s) = single_line_stmt(body) {
                line(out, indent, &format!("repeat ({}) {s}", emit_expr(count)));
            } else {
                line(out, indent, &format!("repeat ({}) begin", emit_expr(count)));
                emit_body(out, indent + 1, body);
                line(out, indent, "end");
            }
        }
        Stmt::Forever(body) => {
            // Body statement tunggal → satu baris (`forever #5 clk = ~clk;`)
            if let Some(s) = single_line_stmt(body) {
                line(out, indent, &format!("forever {s}"));
            } else {
                line(out, indent, "forever begin");
                emit_body(out, indent + 1, body);
                line(out, indent, "end");
            }
        }
        Stmt::Wait { cond, body } => {
            line(out, indent, &format!("wait ({}) begin", emit_expr(cond)));
            emit_body(out, indent + 1, body);
            line(out, indent, "end");
        }
        Stmt::Event { expr, body } => {
            // Body statement tunggal → satu baris (`@(posedge clk) x = y;`)
            if let Some(s) = single_line_stmt(body) {
                line(out, indent, &format!("@({}) {s}", emit_expr(expr)));
            } else {
                line(out, indent, &format!("@({}) begin", emit_expr(expr)));
                emit_body(out, indent + 1, body);
                line(out, indent, "end");
            }
        }
        Stmt::Delay { amt, body } => {
            // Body statement tunggal → satu baris (`#5 clk = ~clk;`)
            if let Some(s) = single_line_stmt(body) {
                line(out, indent, &format!("#{} {s}", emit_expr(amt)));
            } else if matches!(body.as_ref(), Stmt::Block(v) if v.is_empty()) {
                // Delay-only (`#100` di akhir method/block)
                line(out, indent, &format!("#{};", emit_expr(amt)));
            } else {
                line(out, indent, &format!("#{} begin", emit_expr(amt)));
                emit_body(out, indent + 1, body);
                line(out, indent, "end");
            }
        }
        Stmt::ExprStmt(e) => {
            line(out, indent, &format!("{};", emit_expr(e)));
        }
        Stmt::Return(v) => match v {
            Some(e) => line(out, indent, &format!("return {};", emit_expr(e))),
            None => line(out, indent, "return;"),
        },
        Stmt::Break => line(out, indent, "break;"),
        Stmt::Continue => line(out, indent, "continue;"),
        Stmt::VarDecl { names, ty, init } => {
            let init_s = init.as_ref().map(|e| format!(" = {}", emit_expr(e))).unwrap_or_default();
            line(out, indent, &format!("{} {}{};", emit_type(ty), names.join(", "), init_s));
        }
        Stmt::Assert { cond, pass, fail } => {
            // Satu baris bila pass/fail statement call-like (pola testbench
            // `assert (c) $info(...) else $fatal(...);`); fallback multi-baris.
            if let Some(s) = single_line_stmt(stmt) {
                line(out, indent, &s);
            } else {
                line(out, indent, &format!("assert ({})", emit_expr(cond)));
                if let Some(p) = pass {
                    emit_stmt(out, indent + 1, p);
                }
                if let Some(f) = fail {
                    line(out, indent, "else");
                    emit_stmt(out, indent + 1, f);
                }
                // Statement assertion diakhiri `;` (valid SV)
                line(out, indent, ";");
            }
        }
        Stmt::AssertProperty(raw) => {
            // Body RAW (termasuk parens) — emisi 1:1 (MARIA-HDL.md §7.2)
            line(out, indent, &format!("assert property {raw};"));
        }
    }
}

/// Statement sederhana yang bisa di-emit satu baris (tanpa begin/end) —
/// dipakai untuk `assert (...)` dan body `@(...)`/`#amt` yang pendek.
/// None = statement multi-baris → fallback emit_body.
fn single_line_stmt(stmt: &Stmt) -> Option<String> {
    match stmt {
        Stmt::Assign { lhs, rhs, nba, .. } => {
            let op = if *nba { "<=" } else { "=" };
            Some(format!("{} {op} {};", emit_expr(lhs), emit_expr(rhs)))
        }
        // F36/F37: compound assignment / increment compact (body `@(...)`/`#amt`).
        Stmt::CompoundAssign { lhs, op, rhs, .. } => {
            Some(format!("{} {op} {};", emit_expr(lhs), emit_expr(rhs)))
        }
        Stmt::IncDec { lhs, inc, pre, .. } => {
            let op = if *inc { "++" } else { "--" };
            if *pre {
                Some(format!("{}{};", op, emit_expr(lhs)))
            } else {
                Some(format!("{}{};", emit_expr(lhs), op))
            }
        }
        Stmt::ExprStmt(e) => Some(format!("{};", emit_expr(e))),
        // F38: body `do {...} while`/event trigger compact utk `@(...)`/`#amt`.
        Stmt::DoWhile { cond, body } => single_line_stmt(body).map(|s| format!("do {s} while ({});", emit_expr(cond))),
        Stmt::EventTrigger(ev) => Some(format!("-> {};", emit_expr(ev))),
        Stmt::AssertProperty(raw) => Some(format!("assert property {raw};")),
        Stmt::Event { expr, body } => single_line_stmt(body).map(|s| format!("@({}) {s}", emit_expr(expr))),
        Stmt::Delay { amt, body } => single_line_stmt(body).map(|s| format!("#{} {s}", emit_expr(amt))),
        Stmt::Assert { cond, pass, fail } => {
            // Compact HANYA bila pass/fail call-like (`$info(...)` = subroutine
            // call — idiom SVA universal; atau assert property / assert nested).
            // Assign/Event/Delay sebagai pass/fail TIDAK di-compact: tanpa `;`
            // di antara branch, `assert (c) x = 1 else ...` ditolak tool SV
            // strict (blocking assignment butuh `;`).
            let p = match pass.as_ref().map(|s| assert_branch_stmt(s)) {
                Some(Some(s)) => Some(s),
                Some(None) => return None,
                None => None,
            };
            let f = match fail.as_ref().map(|s| assert_branch_stmt(s)) {
                Some(Some(s)) => Some(s),
                Some(None) => return None,
                None => None,
            };
            let c = emit_expr(cond);
            match (p, f) {
                (Some(p), Some(f)) => Some(format!("assert ({c}) {p} else {f};")),
                (Some(p), None) => Some(format!("assert ({c}) {p};")),
                (None, Some(f)) => Some(format!("assert ({c}) else {f};")),
                (None, None) => Some(format!("assert ({c});")),
            }
        }
        _ => None,
    }
}

/// Branch pass/fail assertion yang aman di-compact tanpa semicolon di antara
/// branch. Call-like saja (`$info(...)`, `assert property`, nested `assert`) —
/// semicolon dipasang hanya satu di akhir statement assertion oleh pemanggil.
fn assert_branch_stmt(stmt: &Stmt) -> Option<String> {
    match stmt {
        Stmt::ExprStmt(e) => Some(emit_expr(e)),
        Stmt::AssertProperty(raw) => Some(format!("assert property {raw}")),
        Stmt::Assert { .. } => single_line_stmt(stmt).map(|s| s.trim_end_matches(';').to_string()),
        _ => None,
    }
}

/// Emit rantai `else if` / `else` — `end else if (c) begin` menyambung
/// langsung dari blok sebelumnya agar output satu blok utuh.
fn emit_else_chain(out: &mut String, indent: usize, els: Option<&Stmt>) {
    match els {
        Some(Stmt::If { cond, then, els }) => {
            line(out, indent, &format!("end else if ({}) begin", emit_expr(cond)));
            emit_body(out, indent + 1, then);
            emit_else_chain(out, indent, els.as_deref());
        }
        Some(e) => {
            line(out, indent, "end else begin");
            emit_body(out, indent + 1, e);
            line(out, indent, "end");
        }
        None => {
            line(out, indent, "end");
        }
    }
}

/// Emit isi blok: `Stmt::Block` di-unwrap (tanpa begin/end ganda) karena
/// pemanggil sudah membuka `X begin`. Stmt lain di-emit apa adanya.
fn emit_body(out: &mut String, indent: usize, stmt: &Stmt) {
    match stmt {
        Stmt::Block(stmts) => {
            for s in stmts {
                emit_stmt(out, indent, s);
            }
        }
        other => emit_stmt(out, indent, other),
    }
}

// ── Types ──

/// Emit tipe SV.
pub fn emit_type(t: &MvType) -> String {
    match t {
        MvType::Bit => "bit".into(),
        MvType::Logic(None) => "logic".into(),
        MvType::Logic(Some((a, b))) => format!("logic [{}:{}]", emit_expr(a), emit_expr(b)),
        MvType::Signed(inner) => {
            // `signed logic[8]` → `logic signed [7:0]`
            // `signed bit` → `logic signed` (bit tidak mendukung signed di SV)
            match inner.as_ref() {
                MvType::Logic(r) => match r {
                    Some((a, b)) => format!("logic signed [{}:{}]", emit_expr(a), emit_expr(b)),
                    None => "logic signed".into(),
                },
                MvType::Bit => "logic signed".into(),
                other => format!("signed {}", emit_type(other)),
            }
        }
        MvType::Int => "int".into(),
        MvType::Uint => "logic [31:0]".into(),
        MvType::LongInt => "longint".into(),
        MvType::ULongInt => "longint unsigned".into(),
        MvType::ShortInt => "shortint".into(),
        MvType::Byte => "byte".into(),
        MvType::Real => "real".into(),
        MvType::Time => "time".into(),
        MvType::Str => "string".into(),
        MvType::Named(s, ..) => s.clone(),
        MvType::Array(inner, dims) => {
            let dims_s: Vec<String> = dims.iter().map(|d| format!("[{}]", emit_expr(d))).collect();
            format!("{} {}", emit_type(inner), dims_s.join(" "))
        }
    }
}

/// Tipe dengan padding agar kolom nama rapi (minimal 1 spasi).
fn pad_type(t: String) -> String {
    if t.len() < 6 {
        format!("{t}{}", " ".repeat(6 - t.len()))
    } else {
        format!("{t} ")
    }
}

// ── Expressions ──

/// Emit ekspresi SV.
pub fn emit_expr(e: &Expr) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Sized(Some(w), b, d, ..) => format!("{w}'{b}{d}"),
        Expr::Sized(None, b, d, ..) => format!("'{b}{d}"),
        Expr::Real(v) => {
            let s = v.to_string();
            if s.contains('.') {
                s
            } else {
                format!("{s}.0")
            }
        }
        Expr::Fill(c) => format!("'{c}"),
        Expr::Str(s) => format!("\"{}\"", s),
        Expr::Ident(s, ..) => s.clone(),
        Expr::Scoped(p, i, ..) => format!("{p}::{i}"),
        Expr::Cast { ty, expr, .. } => format!("{}'({})", emit_type(ty), emit_expr(expr)),
        Expr::Unary(op, inner) => {
            if op == "posedge" || op == "negedge" {
                format!("{op} {}", emit_expr(inner))
            } else {
                let inner_s = emit_expr(inner);
                format!("{op}{}", maybe_paren(inner, inner_s))
            }
        }
        // F37: `++x` / `x++` / `--x` / `x--` di level ekspresi (RHS).
        Expr::IncDec { inc, pre, expr } => {
            let op = if *inc { "++" } else { "--" };
            let es = emit_expr(expr);
            if *pre {
                format!("{op}{}", maybe_paren(expr, es))
            } else {
                format!("{}{op}", maybe_paren(expr, es))
            }
        }
        Expr::Binary(op, l, r) => format!("{} {op} {}", emit_expr(l), emit_expr(r)),
        Expr::Ternary(c, t, f) => format!("{} ? {} : {}", emit_expr(c), emit_expr(t), emit_expr(f)),
        Expr::Call(name, args) => {
            let a: Vec<String> = args.iter().map(emit_expr).collect();
            format!("{name}({})", a.join(", "))
        }
        Expr::MethodCall { obj, method, args } => {
            let a: Vec<String> = args.iter().map(emit_expr).collect();
            format!("{}.{method}({})", emit_expr(obj), a.join(", "))
        }
        Expr::Member(obj, f, ..) => format!("{}.{f}", emit_expr(obj)),
        Expr::Index(obj, i) => format!("{}[{}]", emit_expr(obj), emit_expr(i)),
        Expr::Range(obj, a, b) => format!("{}[{}:{}]", emit_expr(obj), emit_expr(a), emit_expr(b)),
        Expr::Concat(parts) => {
            let p: Vec<String> = parts.iter().map(emit_expr).collect();
            format!("{{{}}}", p.join(", "))
        }
        Expr::Replicate(n, inner) => format!("{{{}{{{}}}}}", emit_expr(n), emit_expr(inner)),
        Expr::Paren(inner) => format!("({})", emit_expr(inner)),
        // F12: urutan item inside dijaga 1:1 (`{[1:10], 20}` ≠ `{20, [1:10]}`)
        Expr::Inside { expr, items } => {
            let parts: Vec<String> = items.iter().map(emit_inside_item).collect();
            format!("{} inside {{{}}}", emit_expr(expr), parts.join(", "))
        }
        Expr::Dist { expr, items } => {
            let parts: Vec<String> = items.iter().map(emit_dist_item).collect();
            format!("{} dist {{{}}}", emit_expr(expr), parts.join(", "))
        }
    }
}

/// Emit satu item inside: nilai tunggal atau `[lo:hi]` (F12).
fn emit_inside_item(it: &InsideItem) -> String {
    match it {
        InsideItem::Value(e) => emit_expr(e),
        InsideItem::Range(lo, hi) => format!("[{}:{}]", emit_expr(lo), emit_expr(hi)),
    }
}

/// Emit satu item dist: `[lo:hi] := w` / `v := w` / `v :/ w` (F12).
fn emit_dist_item(it: &DistItem) -> String {
    let op = if it.exact { ":=" } else { ":/" };
    match &it.range {
        Some((lo, hi)) => format!(
            "[{}:{}] {op} {}",
            emit_expr(lo),
            emit_expr(hi),
            emit_expr(&it.weight)
        ),
        None => format!("{} {op} {}", emit_expr(&it.value), emit_expr(&it.weight)),
    }
}

fn maybe_paren(e: &Expr, s: String) -> String {
    if matches!(e, Expr::Binary(..) | Expr::Ternary(..) | Expr::Concat(..)) {
        format!("({s})")
    } else {
        s
    }
}

// ── Helpers ──

fn line(out: &mut String, indent: usize, s: &str) {
    out.push_str(&"    ".repeat(indent));
    out.push_str(s);
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    #[test]
    fn codegen_counter() {
        let src = r#"
module counter #(WIDTH = 8) {
    in  clk, rst_n : bit
    in  enable     : bit
    out count      : logic[WIDTH-1:0]
    seq(clk, rst_n) {
        if (!rst_n) {
            count <= '0
        } else if (enable) {
            count <= count + 1
        }
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "counter");
        assert!(out.sv.contains("module counter"));
        assert!(out.sv.contains("parameter WIDTH = 8"));
        assert!(out.sv.contains("input  bit clk"));
        assert!(out.sv.contains("output logic [WIDTH - 1:0] count"));
        assert!(out.sv.contains("always_ff @(posedge clk or negedge rst_n) begin"));
        assert!(out.sv.contains("count <= '0;"));
        assert!(out.sv.contains("count <= count + 1;"));
        assert!(out.sv.contains("endmodule"));
    }

    #[test]
    fn codegen_traffic() {
        let src = r#"
package traffic_pkg {
    enum State { RED, GREEN, YELLOW }
}

module traffic #(GREEN_T = 30, YELLOW_T = 5) {
    use traffic_pkg::*
    in  clk, rst_n : bit
    out state      : State
    out red, green, yellow : bit

    reg state : State
    reg timer : uint[8]

    seq(clk, rst_n) {
        if (!rst_n) {
            state <= RED
            timer <= 0
        } else {
            case (state) {
                RED: {
                    state <= GREEN
                    timer <= 0
                }
                default: {
                    state <= RED
                }
            }
        }
    }

    comb {
        red    = (state == RED)
        green  = (state == GREEN)
        yellow = (state == YELLOW)
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "traffic");
        // .svh: package + enum
        assert!(out.svh.contains("package traffic_pkg;"));
        assert!(out.svh.contains("typedef enum logic [1:0] { RED, GREEN, YELLOW } State;"));
        assert!(out.svh.contains("`endif"));
        // .sv: import + ports
        assert!(out.sv.contains("`include \"traffic.svh\""));
        assert!(out.sv.contains("import traffic_pkg::*;"));
        assert!(out.sv.contains("output State state"));
        assert!(out.sv.contains("case (state)"));
        assert!(out.sv.contains("default: begin"));
        // reg state = nama port output → tidak dideklarasi ulang
        assert!(!out.sv.contains("State state;"));
    }

    #[test]
    fn codegen_instance_and_generate() {
        let src = r#"
module shiftreg #(N : int = 8) {
    in clk : bit
    in d   : bit
    out q  : logic[N-1:0]
    seq(clk) {
        q[0] <= d
    }
    for i in 1..N {
        seq(clk) {
            q[i] <= q[i-1]
        }
    }
    inst counter_small u_small (.clk, .rst_n, .count(q[3:0]))
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "shiftreg");
        assert!(out.sv.contains("parameter int N = 8"));
        assert!(out.sv.contains("for (genvar i = 1; i < N; i = i + 1) begin : gen_i"));
        assert!(out.sv.contains("q[i] <= q[i - 1];"));
        assert!(out.sv.contains("counter_small u_small ("));
        assert!(out.sv.contains(".clk   (clk),"));
        assert!(out.sv.contains(".rst_n (rst_n),"));
        assert!(out.sv.contains(".count (q[3:0])"));
    }

    #[test]
    fn codegen_types() {
        let src = r#"
type Addr = logic[15:0]
packed struct Packet {
    valid : bit,
    addr  : Addr,
    data  : logic[31:0]
}
enum(3) Color { RED = 0, GREEN = 2, BLUE = 4 }
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "types");
        assert!(out.svh.contains("typedef logic [15:0] Addr;"));
        assert!(out.svh.contains("typedef struct packed {"));
        assert!(out.svh.contains("typedef enum logic [2:0] { RED = 0, GREEN = 2, BLUE = 4 } Color;"));
    }

    #[test]
    fn codegen_func_task() {
        let src = r#"
func clog2(x : int) -> int {
    var r : int = 0
    var n : int = x - 1
    while (n > 0) {
        r = r + 1
        n = n >> 1
    }
    return r
}
task send(data : logic[7:0], out ok : bit) {
    #10
    ok = 1
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "util");
        assert!(out.sv.contains("function int clog2(input int x);"));
        assert!(out.sv.contains("int r = 0;"));
        assert!(out.sv.contains("return r;"));
        assert!(out.sv.contains("task send(inout logic [7:0] data, output bit ok);"));
        // Body `#10` + assignment tunggal → satu baris (polesan F6)
        assert!(out.sv.contains("#10 ok = 1;"));
        assert!(!out.sv.contains("#10 begin"));
    }

    #[test]
    fn codegen_assert_property() {
        // Concurrent assertion: body RAW 1:1 (operator SVA `|->`/`##` bukan
        // token .mv — MARIA-HDL.md §7.2)
        let src = r#"
module m {
    in clk, enable : bit
    in count       : logic[7:0]
    initial {
        assert property (@(posedge clk) enable |-> count == $past(count) + 1)
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "m");
        assert!(
            out.sv.contains("assert property (@(posedge clk) enable |-> count == $past(count) + 1);"),
            "sv: {}",
            out.sv
        );
    }

    #[test]
    fn codegen_testbench() {
        let src = r#"
module counter #(WIDTH = 8) {
    in  clk, rst_n : bit
    in  enable     : bit
    out count      : logic[WIDTH-1:0]
    seq(clk, rst_n) {
        if (!rst_n) {
            count <= '0
        } else if (enable) {
            count <= count + 1
        }
    }
}

module tb_counter {
    in clk, rst_n : bit
    in enable     : bit
    in count      : logic[7:0]

    initial {
        $display("tb_counter: mulai")
        clk = 0
        rst_n = 0
        #20
        rst_n = 1
        enable = 1
        repeat (300) @(posedge clk)
        assert (count > 0) $info("counter ok") else $fatal("counter stuck")
        $finish
    }

    initial {
        forever #5 clk = ~clk
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "tb_counter");
        // $-task sebagai statement (di-lex sebagai Ident("$finish") dll.)
        assert!(out.sv.contains("$display(\"tb_counter: mulai\");"));
        assert!(out.sv.contains("$finish;"));
        // delay + assignment tunggal → satu baris
        assert!(out.sv.contains("forever #5 clk = ~clk;"));
        // assert immediate → satu baris dengan $info/$fatal
        assert!(out.sv.contains(
            "assert (count > 0) $info(\"counter ok\") else $fatal(\"counter stuck\");"
        ));
    }

    #[test]
    fn codegen_program() {
        // Program block (MARIA-HDL.md §7.3)
        let src = r#"
program test_runner {
    in clk : bit
    initial {
        run_test("my_test")
    }
}
"#;
        let file = parse(src).unwrap();
        assert_eq!(file.programs.len(), 1);
        let out = generate(&file, "tb");
        assert!(out.sv.contains("program test_runner ("));
        assert!(out.sv.contains("input  bit clk"));
        assert!(out.sv.contains("initial begin"));
        assert!(out.sv.contains("run_test(\"my_test\");"));
        assert!(out.sv.contains("endprogram"));
    }

    #[test]
    fn codegen_class_uvm() {
        // Class + UVM subset (MARIA-HDL.md §8)
        let src = r#"
class my_test extends uvm_test {
    field count     : uint
    rand field seed : uint
    constraint c { seed > 10, seed < 200 }
    func new(name : string) {
        super.new(name)
    }
    func build_phase() {
        uvm_config_db::set(this, "*.agent", "count", count)
    }
    task run_phase() {
        var seqr : uvm_sequencer
        seqr.start_item(item)
        seqr.finish_item(item)
        #100
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "my_test");
        assert!(out.sv.contains("class my_test extends uvm_test;"));
        assert!(out.sv.contains("logic [31:0] count;"));
        assert!(out.sv.contains("rand logic [31:0] seed;"));
        assert!(out.sv.contains("constraint c {"));
        assert!(out.sv.contains("seed > 10;"));
        assert!(out.sv.contains("seed < 200;"));
        // constructor `new` tanpa tipe return; argumen arah input
        assert!(out.sv.contains("function new(input string name);"));
        assert!(out.sv.contains("super.new(name);"));
        // static call scoped + method call + delay-only
        assert!(out.sv.contains("uvm_config_db::set(this, \"*.agent\", \"count\", count);"));
        assert!(out.sv.contains("function void build_phase();"));
        assert!(out.sv.contains("task run_phase();"));
        assert!(out.sv.contains("uvm_sequencer seqr;"));
        assert!(out.sv.contains("seqr.start_item(item);"));
        assert!(out.sv.contains("seqr.finish_item(item);"));
        assert!(out.sv.contains("#100;"));
        assert!(out.sv.contains("endclass"));
    }

    #[test]
    fn codegen_class_plain() {
        let src = r#"
class counter_model {
    field value : uint
    func new() {
        value = 0
    }
    task tick() {
        value = value + 1
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "model");
        assert!(out.sv.contains("class counter_model;"));
        assert!(out.sv.contains("function new();"));
        assert!(out.sv.contains("task tick();"));
        assert!(out.sv.contains("value = value + 1;"));
        assert!(out.sv.contains("endclass"));
    }

    #[test]
    fn codegen_generate_decl_not_dropped() {
        // Deklarasi di dalam blok generate TIDAK boleh di-drop diam-diam
        // (regresi dari review: arm `_ => {}` lama menelan sig/reg/const).
        let src = r#"
module pipe #(N : int = 4) {
    in clk : bit
    in d   : bit
    out q  : logic[N-1:0]
    for i in 1..N {
        reg tmp : bit
        seq(clk) {
            q[i] <= d
        }
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "pipe");
        assert!(out.sv.contains("        bit tmp;"));
        assert!(out.sv.contains("        always_ff @(posedge clk) begin"));
        assert!(out.sv.contains("            q[i] <= d;"));
    }

    #[test]
    fn codegen_constraint_advanced() {
        // F12: emisi constraint lanjutan 1:1 — inside/dist/if-else/solve
        let src = r#"
class item {
    rand field mode : uint[2]
    rand field addr : uint[8]
    rand field data : uint[8]
    constraint c_adv {
        addr inside {[1:10], 20, 30},
        data dist { 0 := 1, [1:5] :/ 9 },
        if (mode == 1) { addr > 5 } else { addr < 100 },
        solve addr before data
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "item");
        assert!(out.sv.contains("constraint c_adv {"), "sv: {}", out.sv);
        assert!(out.sv.contains("addr inside {[1:10], 20, 30};"));
        assert!(out.sv.contains("data dist {0 := 1, [1:5] :/ 9};"));
        // Constraint `if` SV memakai `{ }` (bukan begin/end)
        assert!(out.sv.contains("if (mode == 1) {"), "sv: {}", out.sv);
        assert!(out.sv.contains("addr > 5;"));
        assert!(out.sv.contains("} else {"));
        assert!(out.sv.contains("addr < 100;"));
        assert!(out.sv.contains("solve addr before data;"));
    }

    #[test]
    fn codegen_interface() {
        // F26: interface + modport (MARIA-HDL.md §6.10) — emisi ke .svh;
        // port module bertipe interface di-emit tanpa arah; seq bisa pakai
        // clock field interface (`iface.clk`).
        let src = r#"
interface axi_lite {
    in  clk : bit
    sig awaddr  : logic[31:0]
    sig awvalid : bit
    sig awready : bit

    modport slave {
        in  awaddr, awvalid
        out awready
    }
}

module dut {
    in axi_if : axi_lite
    out done  : bit
    sig cnt : logic[3:0]
    seq(axi_if.clk) {
        if (axi_if.awvalid && axi_if.awready) {
            cnt <= cnt + 1
            done <= 1
        }
    }
}
"#;
        let file = parse(src).unwrap();
        let out = generate(&file, "axi");
        // .svh: interface + modport + guard
        assert!(out.svh.contains("interface axi_lite;"));
        assert!(out.svh.contains("logic [31:0] awaddr;"));
        assert!(out.svh.contains("modport slave (input awaddr, awvalid, output awready);"));
        assert!(out.svh.contains("endinterface"));
        // .sv: include svh + port interface tanpa arah + seq clock via field
        assert!(out.sv.contains("`include \"axi.svh\""));
        assert!(out.sv.contains("module dut ("));
        assert!(out.sv.contains("    axi_lite axi_if,"), "sv: {}", out.sv);
        assert!(out.sv.contains("output bit done"));
        assert!(out.sv.contains("always_ff @(posedge axi_if.clk) begin"));
        assert!(out.sv.contains("if (axi_if.awvalid && axi_if.awready) begin"));
    }

    #[test]
    fn codegen_interface_only_triggers_svh() {
        // F26: file dengan HANYA interface (tanpa module/program/class/
        // func/task) menghasilkan .svh; .sv KOSONG — F30 fix: file definisi
        // bersama tanpa konten fungsional tidak ditulis oleh `mgen`.
        let src = "interface bus {\n sig a : logic[7:0]\n modport m { in a }\n}\n";
        let out = generate(&parse(src).unwrap(), "bus");
        assert!(out.svh.contains("interface bus;"), "svh: {}", out.svh);
        assert!(out.svh.contains("`endif"));
        assert!(out.sv.is_empty(), "sv: {}", out.sv);
    }

    #[test]
    fn codegen_sig_iface_emits_instance() {
        // F28: `sig x : iface` di module body di-emit sebagai INSTANCE
        // interface (`axi_lite bus();`), bukan deklarasi vif variabel
        // (`axi_lite bus;` — di-parse SV sbg virtual interface var).
        let src = r#"
interface axi_lite {
    sig awaddr : logic[31:0]
}

module tb {
    sig bus : axi_lite
    sig done : bit
    initial {
        bus.awaddr = 32'h10
    }
}
"#;
        let out = generate(&parse(src).unwrap(), "axi");
        assert!(out.sv.contains("axi_lite bus();"), "sv: {}", out.sv);
        assert!(!out.sv.contains("axi_lite bus;"), "sv: {}", out.sv);
        assert!(out.sv.contains("bit done;"));
        assert!(out.sv.contains("bus.awaddr = 32'h10;"));
    }

    #[test]
    fn codegen_cross_file_interface_port_no_dir() {
        // F26 fix review: port module bertipe interface dari FILE LAIN harus
        // tetap di-emit tanpa arah (`bus b`, bukan `input bus b`) — konsisten
        // dgn check_many konteks gabungan. generate_with_ifaces membawa daftar
        // interface global; definisi interface keluar hanya di .svh file asal.
        let src_a = "interface bus {\n sig a : logic[7:0]\n modport m { in a }\n}\n";
        let src_b = "module dut {\n in b : bus\n out y : bit\n comb { y = 0 }\n}\n";
        let fa = parse(src_a).unwrap();
        let fb = parse(src_b).unwrap();
        let ifaces = vec!["bus"];
        // File A: .svh berisi definisi interface
        let oa = generate_with_ifaces(&fa, "bus_def", &ifaces);
        assert!(oa.svh.contains("interface bus;"));
        // File B: port interface TANPA arah (meski bus tak ada di file B)
        let ob = generate_with_ifaces(&fb, "dut", &ifaces);
        assert!(ob.sv.contains("    bus b,"), "sv: {}", ob.sv);
        assert!(!ob.sv.contains("input bus b"), "port interface tidak boleh ada arah");
        // Mode satu-file (generate biasa, iface kosong) → tetap berkualitas:
        // port di-emit dgn arah (fallback aman, bukan interface port)
        let oc = generate(&fb, "dut");
        assert!(oc.sv.contains("input  bus b"), "fallback: {}", oc.sv);
    }

    #[test]
    fn codegen_deterministic() {
        let src = "module a { in clk : bit\n out y : logic[7:0]\n comb { y = x + 1 } }";
        let file = parse(src).unwrap();
        let a = generate(&file, "a").sv;
        let b = generate(&file, "a").sv;
        assert_eq!(a, b);
    }

    #[test]
    fn codegen_svh_only_when_shared_defs() {
        // Tanpa package/typedef → `.svh` kosong & `.sv` tidak include `.svh`.
        let src = "module a { in clk : bit\n out y : logic[7:0]\n comb { y = clk } }";
        let out = generate(&parse(src).unwrap(), "a");
        assert!(out.svh.is_empty(), "svh harus kosong tanpa shared defs: {}", out.svh);
        assert!(!out.sv.contains("`include"), "sv tidak boleh include svh");

        // Dengan package → `.svh` berisi package & `.sv` meng-include.
        let src2 = "package pkg { const N = 4 }\nmodule b { in clk : bit\n out y : logic[3:0]\n comb { y = clk } }";
        let out2 = generate(&parse(src2).unwrap(), "b");
        assert!(out2.svh.contains("package pkg;"), "svh harus berisi package");
        assert!(out2.sv.contains("`include \"b.svh\""), "sv harus include svh");

        // Dengan typedef level file → `.svh` terisi.
        let src3 = "type Addr = logic[15:0]\nmodule c { in a : Addr\n out y : bit\n comb { y = a[0] } }";
        let out3 = generate(&parse(src3).unwrap(), "c");
        assert!(out3.svh.contains("typedef logic [15:0] Addr;"), "svh harus berisi typedef");
        assert!(out3.sv.contains("`include \"c.svh\""));
    }

    #[test]
    fn codegen_type_param() {
        // F32: type param bentuk (A) `T : type = logic[7:0]` →
        // `parameter type T = logic [7:0]`; port bertipe T tetap `T d`.
        let src = "module m #(T : type = logic[7:0], N = 2) {\n    in  d : T\n    out q : T\n}\n";
        let out = generate(&parse(src).unwrap(), "m");
        assert!(out.sv.contains("parameter type T = logic [7:0]"), "sv: {}", out.sv);
        assert!(out.sv.contains("parameter N = 2"), "sv: {}", out.sv);
        assert!(out.sv.contains("input  T d"), "sv: {}", out.sv);
        assert!(out.sv.contains("output T q"), "sv: {}", out.sv);
    }

    #[test]
    fn codegen_type_param_kw_syntax() {
        // F32: bentuk (B) `type T = logic[15:0]` (kata kunci type di awal)
        // → emit `parameter type T = logic [15:0]`.
        let src = "module m #(type T = logic[15:0]) {\n    sig x : T\n}\n";
        let out = generate(&parse(src).unwrap(), "m");
        assert!(out.sv.contains("parameter type T = logic [15:0]"), "sv: {}", out.sv);
        assert!(out.sv.contains("T x;"), "sv: {}", out.sv);
    }

    #[test]
    fn codegen_cast() {
        // F33: type cast `T'(expr)` di-emit apa adanya ke SV.
        let src = "type Word16 = logic[15:0]\nmodule m {\n    in  a : logic[15:0]\n    out w : Word16\n    out b : bit\n    comb {\n        w = Word16'(a)\n        b = logic'(a[0])\n    }\n}\n";
        let out = generate(&parse(src).unwrap(), "m");
        assert!(out.sv.contains("w = Word16'(a);"), "sv: {}", out.sv);
        assert!(out.sv.contains("b = logic'(a[0]);"), "sv: {}", out.sv);
    }
}
